

// ===== LOGIN =====
const usuarios = [
  { usuario: "cadastro", senha: "cadastro2025" },
  { usuario: "user", senha: "abcd" }
];

function validarLogin() {
  const user = document.getElementById("loginUser").value.trim();
  const pass = document.getElementById("loginPass").value.trim();
  const erro = document.getElementById("loginError");

  const autorizado = usuarios.find(u => u.usuario === user && u.senha === pass);

  if (autorizado) {
    document.getElementById("loginScreen").style.display = "none";
    document.getElementById("mainApp").style.display = "block";
  } else {
    erro.textContent = "Usuário ou senha inválidos!";
  }
}

// ==== LISTAS EXTRAS GERADAS DA PLANILHA ====
const LINHAS = [
  { codigo: "C1K0", nome: "ACESSORIOS" },
  { codigo: "A0F0", nome: "LINHA DE VIDA HORIZONTAL" },
  { codigo: "A0D0", nome: "LINHA DE VIDA VERTICAL" },
  { codigo: "MANU", nome: "MANUTENCAO" },
  { codigo: "A0E0", nome: "ACESSO E RESGATE" },
  { codigo: "B4J0", nome: "ACESSORIOS ESPACO CONFINADO" },
  { codigo: "1006", nome: "VENTILACAO (ESP.CONFINADO)" },
  { codigo: "A0A0", nome: "SERVICOS DE ENGENHARIA" },
  { codigo: "B4I0", nome: "MONITOR DE GAS" },
  { codigo: "A0B1", nome: "TRAVA-QUEDA RETRATIL" },
  { codigo: "B1B0", nome: "CALCAS" },
  { codigo: "B9A4", nome: "CUTTER NIVEL 5" },
  { codigo: "B9A5", nome: "ACESSORIOS CUTTER" },
  { codigo: "A0B2", nome: "TRAVA-QUEDA CABO DE ACO" },
  { codigo: "B4G1", nome: "INSU./EXA. AREA N CLASSIFICADA" },
  { codigo: "B3D1", nome: "MANGUEIRAS" },
  { codigo: "A0C0", nome: "DISPOSITIVO DE ANCORAGEM" },
  { codigo: "B1J0", nome: "ACESSORIOS" },
  { codigo: "B4H1", nome: "DUTO AREA NAO CLASSIFICADA" },
  { codigo: "B3E0", nome: "ACESSORIOS COMBATE INCENDIO" },
  { codigo: "A0B3", nome: "TRAVA-QUEDA CORDA" },
  { codigo: "B4B0", nome: "TRIPE" },
  { codigo: "B4D0", nome: "3WAY" },
  { codigo: "B5I0", nome: "DIVERSO SINALIZACAO" },
  { codigo: "ADMI", nome: "ADMINISTRATIVO" },
  { codigo: "8000", nome: "CUTTER" },
  { codigo: "1000", nome: "ESPACO CONFINADO" },
  { codigo: "FIXO", nome: "ATIVO FIXO" },
  { codigo: "B7B0", nome: "CADEADO" },
  { codigo: "B9A6", nome: "CUTTER DESCONTINUADO" },
  { codigo: "B4C0", nome: "GUINCHO" },
  { codigo: "A8A0", nome: "VESTIMENTA IMPERMEAVEL" },
  { codigo: "SPA0", nome: "PROJETO/ENGE. DESCONTINUADO" },
  { codigo: "B3D3", nome: "LIQUIDO GERADOR DE ESPUMA LGE" },
  { codigo: "A8G0", nome: "IMPERMEAVEL DESCONTINUADO" },
  { codigo: "A2A0", nome: "RESPIRADOR DESCART. C/ VALVULA" },
  { codigo: "A3A0", nome: "VESTIMENTA ARCO ELETRICO CAT.1" },
  { codigo: "A5C5", nome: "PROTECAO QUIMICA DESCONTINUADO" },
  { codigo: "A6B1", nome: "LUVA PROCEDIMENTO" },
  { codigo: "A6D0", nome: "LUVA PARA RISCO MECANICO" },
  { codigo: "A8F0", nome: "IMPERMEAVEL DESCONTINUADO" },
  { codigo: "A8B0", nome: "IMPERMEAVEL DESCONTINUADO" },
  { codigo: "0402", nome: "PALMILHAS" },
  { codigo: "A7E0", nome: "ACESSORIOS CALCADO" },
  { codigo: "B0A0", nome: "CAPACETE" },
  { codigo: "B0B0", nome: "BONE CASQUETE" },
  { codigo: "B5B0", nome: "CONE / BANDEIROLA SINALIZACAO" },
  { codigo: "B5C0", nome: "CAVALETE/PEDESTAL SINALIZACAO" },
  { codigo: "B5A0", nome: "COLETE SINALIZACAO" },
  { codigo: "A7A0", nome: "BOTA PVC" },
  { codigo: "A7A3", nome: "BOTA PU" },
  { codigo: "C0B0", nome: "PORTA FERRAMENTA" },
  { codigo: "A7A1", nome: "BOTA BORRACHA" },
  { codigo: "A3A3", nome: "VESTIMENTA ARCO ELETRICO CAT.4" },
  { codigo: "A7A2", nome: "BOTA VAQUETA" },
  { codigo: "A7D0", nome: "SAPATO COURO" },
  { codigo: "A3A7", nome: "VESTIMENTA OUTROS" },
  { codigo: "A7B0", nome: "BOTINA COURO" },
  { codigo: "A7B3", nome: "BOTINA PU" },
  { codigo: "A7D4", nome: "DESCONTINUADO" },
  { codigo: "A7B1", nome: "BOTINA NOBUCK" },
  { codigo: "A7F0", nome: "COTURNO COURO" },
  { codigo: "0340", nome: "Diversos" },
  { codigo: "A7G0", nome: "SANDALIA NOBUCK" },
  { codigo: "03", nome: "MEMBROS SUPERIORES" },
  { codigo: "A7C3", nome: "TENIS PU" },
  { codigo: "A7B4", nome: "BOTINA MICROFIBRA" },
  { codigo: "A7D1", nome: "SAPATO MICRO FIBRA" },
  { codigo: "B1F0", nome: "BONES" },
  { codigo: "A4A0", nome: "OCULOS COMUNS" },
  { codigo: "C7A0", nome: "CHUVEIRO" },
  { codigo: "B9", nome: "Cutter" },
  { codigo: "X0X0", nome: "DEMANDA DIRECIONADA" },
  { codigo: "A7F1", nome: "CALCADO DESCONTINUADO" },
  { codigo: "B1I0", nome: "AVENTAIS" },
  { codigo: "A7C0", nome: "TENIS COURO" },
  { codigo: "A3A4", nome: "VESTIMENTA PARA SOLDA" },
  { codigo: "A7C1", nome: "TENIS MICRO FIBRA" },
  { codigo: "A5B1", nome: "PROTECAO QUIMICA DESCONTINUADO" },
  { codigo: "B3A5", nome: "BALACLAVA COMBATE A ICENDIO" },
  { codigo: "A5B0", nome: "AGENTE QUIMICO (S)-PROT. 5 E 6" },
  { codigo: "A6B0", nome: "LUVA PARA RISCO QUIMICO" },
  { codigo: "55", nome: "DIVERSOS" },
  { codigo: "AO00", nome: "ACESSORIOS EM GERAL" },
  { codigo: "0405", nome: "BOTINAS" },
  { codigo: "A7B2", nome: "BOTINA BORRACHA" },
  { codigo: "A7A4", nome: "BOTA EVA" },
  { codigo: "A7D3", nome: "SAPATO EVA" },
  { codigo: "0410", nome: "Fusiveis" },
  { codigo: "A9B0", nome: "TOUCA DESCARTAVEL" },
  { codigo: "A9G0", nome: "DIVERSOS DESCARTAVEL" },
  { codigo: "A6F0", nome: "LUVA DIVERSOS" },
  { codigo: "A9D0", nome: "SAPATILHA DESCARTAVEL" },
  { codigo: "A3A1", nome: "VESTIMENTA ARCO ELETRICO CAT.2" },
  { codigo: "A4B1", nome: "ACESSORIOS P/ PROTECAO FACIAL" },
  { codigo: "B2A0", nome: "CREME PARA MAOS" },
  { codigo: "A5A0", nome: "AGENTE QUIMICO (L/G) - PROT. 1" },
  { codigo: "B3B4", nome: "ARMARIOS E ABRIGOS" },
  { codigo: "0435", nome: "COTURNO" },
  { codigo: "A2E0", nome: "EQUIPAMENTO AUTONOMO" },
  { codigo: "0415", nome: "TENIS" },
  { codigo: "0401", nome: "BOTAS" },
  { codigo: "B1A0", nome: "CAMISAS" },
  { codigo: "A8I0", nome: "IMPERMEAVEL DESCONTINUADO" },
  { codigo: "4600", nome: "PROTECAO A CABECA" },
  { codigo: "B1D0", nome: "MACACOES" },
  { codigo: "B3A0", nome: "VESTIMENTAS COMBATE A INCENDIO" },
  { codigo: "C6A0", nome: "JAPONA PROTECAO TERMICA (FRIO)" },
  { codigo: "C6C0", nome: "BLUSAO PROTECAO TERMICA (FRIO)" },
  { codigo: "A9C0", nome: "AVENTAL DESCARTAVEL" },
  { codigo: "4605", nome: "CAPUZ / TOUCA" },
  { codigo: "B1C0", nome: "CONJUNTOS" },
  { codigo: "A5C7", nome: "PROTECAO QUIMICA DESCONTINUADO" },
  { codigo: "0735", nome: "CAPUZES/TOUCAS" },
  { codigo: "B1H0", nome: "PERNEIRAS" },
  { codigo: "B7E0", nome: "ACESSORIOS DE BLOQUEIO" },
  { codigo: "A3A5", nome: "VESTI. RESPINGO METAL FUNDIDO" },
  { codigo: "C1D1", nome: "EXTINTOR" },
  { codigo: "B3D0", nome: "EXTINTORES" },
  { codigo: "4601", nome: "CAPACETES" },
  { codigo: "A4B0", nome: "PROTETOR FACIAL SIMPLES" },
  { codigo: "A1A0", nome: "ABAFADOR TIPO CONCHA DIVERSOS" },
  { codigo: "A2C1", nome: "ACESSORIOS RESP. AR COMPRIMIDO" },
  { codigo: "A2F0", nome: "CARTUCHO / FILTRO" },
  { codigo: "A2D0", nome: "ACESSORIOS E PECAS PROT. RESP." },
  { codigo: "A1B0", nome: "PLUG DE INSERCAO" },
  { codigo: "A4C3", nome: "ACESSORIOS MASCARA SOLDA" },
  { codigo: "A1A2", nome: "ABAFADOR CONCHA ACOPLAVEL" },
  { codigo: "A1D0", nome: "ACESSORIOS PROTECAO AUDITIVA" },
  { codigo: "A2B0", nome: "RESP.  REUTIL. SEMI-FACIAL" },
  { codigo: "C1E0", nome: "MANGUEIRAS" },
  { codigo: "A2B2", nome: "PROT. RESPIRAT. DESCONTINUADO" },
  { codigo: "A2A1", nome: "RESPIRADOR DESCART. S/ VALVULA" },
  { codigo: "A1A1", nome: "ABAFADOR CONCHA HASTE FIXA" },
  { codigo: "A1C0", nome: "PROTETOR AUDITIVO ATIVO" },
  { codigo: "C5B0", nome: "FITA PARA IMPRESSORA" },
  { codigo: "A9A0", nome: "MASCARA DESCARTAVEL" },
  { codigo: "B5D0", nome: "FITA SINALIZACAO" },
  { codigo: "A2B1", nome: "RESP. REUTIL. FACIAL INTEIRA" },
  { codigo: "A2C4", nome: "PROTECAO RESP. DESCONTINUADO" },
  { codigo: "0535", nome: "CARTUCHOS/FILTRO" },
  { codigo: "0540", nome: "Eletrodutos E Conexoes" },
  { codigo: "A4B3", nome: "PROTECAO VISUAL DESCONTINUADO" },
  { codigo: "05", nome: "RESPIRATORIA" },
  { codigo: "C1E1", nome: "MANGUEIRAS" },
  { codigo: "A4A3", nome: "ACESSORIOS OCULOS" },
  { codigo: "B3B0", nome: "CAPACETE COMBATE A ICENDIO" },
  { codigo: "A2C3", nome: "ACESSORIOS RESP. MOTORIZADO" },
  { codigo: "A3C0", nome: "PROT. TERMICA DESCONTINUADO" },
  { codigo: "A6C0", nome: "LUVA PARA RISCO BIOLOGICO" },
  { codigo: "A5A2", nome: "AGENTE QUIMICO (L/G) - PROT. 3" },
  { codigo: "B2E0", nome: "PROTECAO SOLAR" },
  { codigo: "B2F0", nome: "DOSADOR" },
  { codigo: "A5A3", nome: "AGENTE QUIMICO (L/G) - PROT. 4" },
  { codigo: "A6A0", nome: "LUVA PARA RISCO TERMICO" },
  { codigo: "A7C2", nome: "TENIS NOBUCK" },
  { codigo: "0395", nome: "MANGOTES/MANGAS" },
  { codigo: "A6", nome: "Luvas" },
  { codigo: "0820", nome: "Madeira E Derivados" },
  { codigo: "0335", nome: "LUVAS ALGODAO/FIOS SINTETICOS" },
  { codigo: "A3A6", nome: "VESTIMENTA PROTECAO MECANICA" },
  { codigo: "A9F0", nome: "MANGOTE DESCARTAVEL" },
  { codigo: "A8", nome: "Impermeavel" },
  { codigo: "C6D0", nome: "CAPA 7/8 PROT. TERMICA (FRIO)" },
  { codigo: "2010", nome: "COLETES" },
  { codigo: "A5A4", nome: "PROTECAO QUIMICA DESCONTINUADO" },
  { codigo: "B1E0", nome: "JARDINEIRAS" },
  { codigo: "C6F0", nome: "ACESSORIOS PROT. TERMICA(FRIO)" },
  { codigo: "A6DA", nome: "LUVA DESCONTINUADO" },
  { codigo: "A6A1", nome: "LUVA DESCONTINUADO" },
  { codigo: "A7G1", nome: "SANDALIA COURO" },
  { codigo: "4700", nome: "CREMES DE PROTECAO" },
  { codigo: "B2D0", nome: "SABONETE EM GERAL" },
  { codigo: "B2C1", nome: "REPELENTE" },
  { codigo: "0505", nome: "SEMI-FACIAL" },
  { codigo: "A4B2", nome: "PROTECAO VISUAL DESCONTINUADO" },
  { codigo: "A4C0", nome: "MASCARA DE SOLDA SIMPLES" },
  { codigo: "A0A2", nome: "CINTURAO ABDOMINAL" },
  { codigo: "4010", nome: "DETECTOR DE GASES" },
  { codigo: "A1A3", nome: "ABAFADOR CONCHA HASTE NA NUCA" },
  { codigo: "A4C1", nome: "MASCARA SOLDA ESCURECIME. AUT." },
  { codigo: "B7A0", nome: "VALVULA DE BLOQUEIO" },
  { codigo: "A4A1", nome: "OCULOS AMPLA VISAO" },
  { codigo: "4604", nome: "MASCARAS SOLDADORES" },
  { codigo: "C7B0", nome: "CHUVEIRO LAVA-OLHOS" },
  { codigo: "C8A0", nome: "MACAS" },
  { codigo: "B3D2", nome: "DETECTORES DE FUMACA" },
  { codigo: "0141", nome: "CADEIRA SUSPENSA (ALTURA)" },
  { codigo: "0490", nome: "ACESSORIOS" },
  { codigo: "A2C2", nome: "RESPIRADOR MOTORIZADO" },
  { codigo: "A4A4", nome: "PROTECAO VISUAL DESCONTINUADO" },
  { codigo: "0701", nome: "OCULOS" },
  { codigo: "A4C2", nome: "MASCARA SOLDA C/ PROT. RESPI." },
  { codigo: "A8D0", nome: "IMPERMEAVEL DESCONTINUADO" },
  { codigo: "B3F0", nome: "HIDRAULICA" },
  { codigo: "0702", nome: "LENTES" },
  { codigo: "A6B4", nome: "LUVA DESCONTINUADO" },
  { codigo: "A404", nome: "Z3R0" },
  { codigo: "A4A2", nome: "OCULOS COM GRAU" },
  { codigo: "56", nome: "ESPELHOS" },
  { codigo: "B7A3", nome: "BLOQUEIO DESCONTINUADO" },
  { codigo: "B5G0", nome: "PELICULA SINALIZACAO" },
  { codigo: "A3D2", nome: "PROT. TERMICA DESCONTINUADO" },
  { codigo: "B5E0", nome: "CORRENTE SINALIZACAO" },
  { codigo: "C1A3", nome: "FITA" },
  { codigo: "A6B2", nome: "LUVA DESCONTINUADO" },
  { codigo: "B5H0", nome: "PLACA SINALIZACAO" },
  { codigo: "B5J0", nome: "BARRA /BARREIRA SINALIZACAO" },
  { codigo: "B4E0", nome: "ESTACAO FILTRANTE" },
  { codigo: "B7G0", nome: "CARTAO IDENTIFICACAO BLOQUEIO" },
  { codigo: "B7", nome: "Bloqueio" },
  { codigo: "B0", nome: "PROTECAO CRANIANA" },
  { codigo: "A6A3", nome: "LUVA DESCONTINUADO" },
  { codigo: "0301", nome: "LUVAS NITRILICAS" },
  { codigo: "A1B2", nome: "PROT. AUDITIVA DESCONTINUADO" },
  { codigo: "A3J0", nome: "PROT. TERMICA DESCONTINUADO" },
  { codigo: "A6A5", nome: "LUVA DESCONTINUADO" },
  { codigo: "A6D7", nome: "LUVA DESCONTINUADO" },
  { codigo: "A2", nome: "Protecao Respiratoria" },
  { codigo: "2000", nome: "SINALIZACAO" },
  { codigo: "A0A1", nome: "CINTURAO PARAQUEDISTA" },
  { codigo: "B2B0", nome: "DESENGRAXANTE" },
  { codigo: "A3K0", nome: "PROT. TERMICA DESCONTINUADO" },
  { codigo: "B1G0", nome: "JAPONAS" },
  { codigo: "A4C5", nome: "PROTECAO VISUAL DESCONTINUADO" },
  { codigo: "B800", nome: "ERGONOMIA" },
  { codigo: "C1", nome: "M.R.O." },
  { codigo: "C7E0", nome: "ACESSORIOS CHUVEIRO/LAVA-OLHOS" },
  { codigo: "A3B6", nome: "PROT. TERMICA DESCONTINUADO" },
  { codigo: "B2C0", nome: "ANTISSEPTICO" },
  { codigo: "0331", nome: "LUVA LATEX C/SUPORTE TEXTIL" },
  { codigo: "B5F0", nome: "TELA SINALIZACAO" },
  { codigo: "A6D5", nome: "LUVA DESCONTINUADO" },
  { codigo: "A8H0", nome: "IMPERMEAVEL DESCONTINUADO" },
  { codigo: "A3D4", nome: "PROT. TERMICA DESCONTINUADO" },
  { codigo: "C1A4", nome: "TRAVA" },
  { codigo: "A3F4", nome: "PROT. TERMICA DESCONTINUADO" },
  { codigo: "A6D2", nome: "LUVA DESCONTINUADO" },
  { codigo: "A3C1", nome: "PROT. TERMICA DESCONTINUADO" },
  { codigo: "C6B0", nome: "CALCA PROTECAO TERMICA (FRIO)" },
  { codigo: "4AA0", nome: "Bidin" },
  { codigo: "C1D0", nome: "EQUIPAMENTOS" },
  { codigo: "C6E0", nome: "MEIA PROTECAO TERMICA (FRIO)" },
  { codigo: "A0A4", nome: "TALABARTE" },
  { codigo: "0220", nome: "Componentes E Acessorios" },
  { codigo: "A6E5", nome: "LUVA ISOLANTE  CLASSE - 4" },
  { codigo: "A6E0", nome: "LUVA ISOLANTE  CLASSE - 00" },
  { codigo: "A6E1", nome: "LUVA ISOLANTE  CLASSE - 0" },
  { codigo: "A6E2", nome: "LUVA ISOLANTE  CLASSE - 1" },
  { codigo: "A6E3", nome: "LUVA ISOLANTE  CLASSE - 2" },
  { codigo: "C0A0", nome: "BOLSA" },
  { codigo: "B1", nome: "Uniformes" },
  { codigo: "0124", nome: "VARA DE MANOBRA (ALTURA)" },
  { codigo: "A0B0", nome: "TRAVA-QUEDA DIVERSOS" },
  { codigo: "C1A0", nome: "FIXACAO" },
  { codigo: "A0A5", nome: "ALTURA DESCONTINUADO" },
  { codigo: "C5C0", nome: "ETIQUETA PARA IMPRESSORA" },
  { codigo: "C9", nome: "AUTOMACAO" },
  { codigo: "C0C0", nome: "MOCHILA" },
  { codigo: "A3J2", nome: "PROT. TERMICA DESCONTINUADO" },
  { codigo: "A8C0", nome: "IMPERMEAVEL DESCONTINUADO" },
  { codigo: "A8E0", nome: "IMPERMEAVEL DESCONTINUADO" },
  { codigo: "C6", nome: "Protecao Termica (Frio)" },
  { codigo: "C8A2", nome: "KIT PRIMEIROS SOCORROS" },
  { codigo: "A6E4", nome: "LUVA ISOLANTE  CLASSE - 3" },
  { codigo: "C2A0", nome: "MEIO AMBIENTE" },
  { codigo: "A3J4", nome: "PROT. TERMICA DESCONTINUADO" },
  { codigo: "0007", nome: "Produto de Venda" },
  { codigo: "B3A1", nome: "BLUSAO 3/4 COMBATE A INCENDIO" },
  { codigo: "2040", nome: "PEDESTAL" },
  { codigo: "C1B0", nome: "ALARME E BUZINA" },
  { codigo: "0110", nome: "TALABARTES  (ALTURA)" },
  { codigo: "C8A1", nome: "IMOBILIZACAO" },
  { codigo: "4606", nome: "ACESSORIOS" },
  { codigo: "B2", nome: "Higiene,Saude e Prot da Pele" },
  { codigo: "C1G0", nome: "LENCOIS" },
  { codigo: "A0A3", nome: "CINTURAO CADEIRINHA" },
  { codigo: "0127", nome: "MOSQUETAO (ALTURA)" },
  { codigo: "2015", nome: "CORRENTES" },
  { codigo: "5BP3", nome: "Adesivo" },
  { codigo: "0310", nome: "Medidores De Pressao" },
  { codigo: "A6D6", nome: "LUVA DESCONTINUADO" },
  { codigo: "A6A9", nome: "LUVA DESCONTINUADO" },
  { codigo: "B4H0", nome: "DUTO AREA CLASSIFICADA" },
  { codigo: "B9A0", nome: "CUTTER NIVEL 1" },
  { codigo: "C9A0", nome: "SISTEMA ANTI-ATROPELAMENTO" },
  { codigo: "A3D0", nome: "PROT. TERMICA DESCONTINUADO" },
  { codigo: "4602", nome: "CARNEIRAS" },
  { codigo: "A3H4", nome: "PROT. TERMICA DESCONTINUADO" },
  { codigo: "CIK0", nome: "ACESSORIOS" },
  { codigo: "B3", nome: "COMBATE A INCENDIO" },
  { codigo: "CB", nome: "CONE P/BIRUTA" },
  { codigo: "A0A8", nome: "MOSQUETOES E CONECTORES" },
  { codigo: "PLLT", nome: "PALLET" },
  { codigo: "PLT", nome: "PALETO" },
  { codigo: "IDM0", nome: "ITENS DE MRO" },
  { codigo: "F3R0", nome: "FERRAMENTAS" },
  { codigo: "C0V3", nome: "CHAVE FERRAMENTA" },
  { codigo: "ZKA3", nome: "TAPETE ISOLANTE" }
];

const TIPOS_CONVERSAO = [
  { codigo: "ME", nome: "MERCADORIA" },
  { codigo: "MP", nome: "MATERIA PRIMA" },
  { codigo: "MC", nome: "MATERIAL CONSUMO" },
  { codigo: "BN", nome: "BENEFICIAMENTO" },
  { codigo: "OI", nome: "OUTROS INSUMOS" },
  { codigo: "AI", nome: "ATIVO IMOBILIZADO" },
  { codigo: "EM", nome: "EMBALAGENS" },
  { codigo: "PI", nome: "PRODUTO INTERMEDIARIO" },
  { codigo: "Z3R0", nome: "NÃO LOCALIZADO" },
  { codigo: "RV", nome: "REVENDA DE PRODUTOS NACIONAL E/OU IMPORTADO" },
  { codigo: "MO", nome: "MAO DE OBRA" },
  { codigo: "MT", nome: "MANUTENCAO DE TRAVA QUEDAS" },
  { codigo: "AF", nome: "ATIVO FIXO" },
  { codigo: "MA", nome: "MANUTENCAO DE ATIVOS" },
  { codigo: "GG", nome: "GASTOS GERAIS" },
  { codigo: "SE", nome: "NÃO LOCALIZADO" },
  { codigo: "MI", nome: "MATERIAL DE INFORMATICA" },
  { codigo: "PA", nome: "PRODUTO ACABADO" },
  { codigo: "PC", nome: "PAGAMENTO DE CONTA" },
  { codigo: "DN", nome: "DISTRIBUICAO DE PRODUTO NACIONAL" },
  { codigo: "PV", nome: "PRODUTO VEICULO" },
  { codigo: "SP", nome: "SUBPRODUTO" },
  { codigo: "M", nome: "M - Multiplicador" },
  { codigo: "D", nome: "D - Divisor" }
];

const BLOQUEIOS = [
  { codigo: "1", nome: "CA VENCIDO/PROX. VENC." },
  { codigo: "2", nome: "DESCONTINUADO" },
  { codigo: "3", nome: "SUSPENSO PELO FORNECEDOR" },
  { codigo: "4", nome: "SUSPENSO PELA QUALIDADE" },
  { codigo: "5", nome: "SUSPENSO PELO COMERCIAL - SP" }
];

const LOJAS = [
  { codigo: "1", nome: "1" },
  { codigo: "2", nome: "2" },
  { codigo: "3", nome: "3" },
  { codigo: "4", nome: "4" },
  { codigo: "5", nome: "5" },
  { codigo: "6", nome: "6" },
  { codigo: "7", nome: "7" },
  { codigo: "8", nome: "8" },
  { codigo: "9", nome: "9" },
  { codigo: "10", nome: "10" },
  { codigo: "11", nome: "11" },
  { codigo: "12", nome: "12" },
  { codigo: "13", nome: "13" },
  { codigo: "14", nome: "14" },
  { codigo: "15", nome: "15" },
  { codigo: "16", nome: "16" },
  { codigo: "17", nome: "17" },
  { codigo: "18", nome: "18" },
  { codigo: "19", nome: "19" },
  { codigo: "20", nome: "20" },
  { codigo: "21", nome: "21" },
  { codigo: "22", nome: "22" },
  { codigo: "23", nome: "23" },
  { codigo: "24", nome: "24" },
  { codigo: "25", nome: "25" },
  { codigo: "26", nome: "26" },
  { codigo: "27", nome: "27" },
  { codigo: "28", nome: "28" },
  { codigo: "29", nome: "29" },
  { codigo: "30", nome: "30" },
  { codigo: "31", nome: "31" },
  { codigo: "32", nome: "32" },
  { codigo: "33", nome: "33" },
  { codigo: "34", nome: "34" },
  { codigo: "35", nome: "35" },
  { codigo: "36", nome: "36" },
  { codigo: "37", nome: "37" },
  { codigo: "38", nome: "38" },
  { codigo: "39", nome: "39" },
  { codigo: "40", nome: "40" },
  { codigo: "41", nome: "41" },
  { codigo: "42", nome: "42" },
  { codigo: "43", nome: "43" },
  { codigo: "44", nome: "44" },
  { codigo: "45", nome: "45" },
  { codigo: "46", nome: "46" },
  { codigo: "47", nome: "47" },
  { codigo: "48", nome: "48" },
  { codigo: "49", nome: "49" },
  { codigo: "50", nome: "50" },
  { codigo: "51", nome: "51" },
  { codigo: "52", nome: "52" },
  { codigo: "53", nome: "53" },
  { codigo: "54", nome: "54" },
  { codigo: "55", nome: "55" },
  { codigo: "56", nome: "56" },
  { codigo: "57", nome: "57" },
  { codigo: "58", nome: "58" },
  { codigo: "59", nome: "59" },
  { codigo: "60", nome: "60" },
  { codigo: "61", nome: "61" },
  { codigo: "62", nome: "62" },
  { codigo: "63", nome: "63" },
  { codigo: "64", nome: "64" },
  { codigo: "65", nome: "65" },
  { codigo: "66", nome: "66" },
  { codigo: "67", nome: "67" },
  { codigo: "68", nome: "68" },
  { codigo: "69", nome: "69" },
  { codigo: "70", nome: "70" },
  { codigo: "71", nome: "71" },
  { codigo: "72", nome: "72" },
  { codigo: "73", nome: "73" },
  { codigo: "74", nome: "74" },
  { codigo: "75", nome: "75" },
  { codigo: "76", nome: "76" },
  { codigo: "77", nome: "77" },
  { codigo: "78", nome: "78" },
  { codigo: "79", nome: "79" },
  { codigo: "80", nome: "80" },
  { codigo: "81", nome: "81" },
  { codigo: "82", nome: "82" },
  { codigo: "83", nome: "83" },
  { codigo: "84", nome: "84" },
  { codigo: "85", nome: "85" },
  { codigo: "86", nome: "86" },
  { codigo: "87", nome: "87" },
  { codigo: "88", nome: "88" },
  { codigo: "89", nome: "89" },
  { codigo: "90", nome: "90" },
  { codigo: "91", nome: "91" },
  { codigo: "92", nome: "92" },
  { codigo: "93", nome: "93" },
  { codigo: "94", nome: "94" },
  { codigo: "95", nome: "95" },
  { codigo: "96", nome: "96" },
  { codigo: "97", nome: "97" },
  { codigo: "98", nome: "98" },
  { codigo: "99", nome: "99" },
  { codigo: "1", nome: "1" },
  { codigo: "2", nome: "2" }
];


const UNIDADES = [
  { codigo: "PR", nome: "PAR" },
  { codigo: "PC", nome: "PEÇA" },
  { codigo: "CX", nome: "CAIXA" },
  { codigo: "CJ", nome: "CONJUNTO" },
  { codigo: "CT", nome: "CARTELA" },
  { codigo: "DZ", nome: "DUZIA" },
  { codigo: "G", nome: "GRAMAS" },
  { codigo: "GL", nome: "GALÃO" },
  { codigo: "KT", nome: "KIT" },
  { codigo: "L", nome: "LITRO" },
  { codigo: "LA", nome: "LATA" },
  { codigo: "PT", nome: "PACOTE" },
  { codigo: "RL", nome: "ROLO" },
  { codigo: "TB", nome: "TUBO" },
  { codigo: "UN", nome: "UNIDADE" }
];

const ARMAZENS = [
  { codigo: "1", nome: "1.0" }
];



// Função genérica para popular datalists sem duplicação
function popularLista(id, lista) {
  const datalist = document.getElementById(id);
  if (!datalist) return;
  datalist.innerHTML = "";
  lista.forEach(item => {
    const option = document.createElement("option");
    option.value = item.nome;
    option.dataset.codigo = item.codigo;
    datalist.appendChild(option);
  });
}

popularLista("listaUnidades", UNIDADES);

// ==== RESTANTE DO SCRIPT ORIGINAL ====

// script_atualizado.js — gerado a partir da planilha

const MARCAS_NUM = {
  "MMM": "001",
  "AFX": "005",
  "ASY": "006",
  "ARS": "008",
  "ASL": "009",
  "BBS": "010",
  "BLA": "011",
  "BAL": "012",
  "BDI": "013",
  "BSA": "014",
  "BLD": "015",
  "CLR": "016",
  "CGE": "017",
  "CRL": "018",
  "CEN": "019",
  "CIA": "020",
  "CFO": "021",
  "CNX": "022",
  "DAY": "023",
  "DOG": "024",
  "DAR": "025",
  "DPT": "026",
  "DVS": "027",
  "ERF": "028",
  "RCE": "029",
  "FAZ": "030",
  "FZA": "031",
  "FAO": "032",
  "FFX": "033",
  "FNA": "034",
  "FIA": "035",
  "HCS": "036",
  "IDL": "037",
  "IDE": "038",
  "ILS": "039",
  "IFY": "040",
  "INE": "041",
  "IAR": "042",
  "ITP": "043",
  "JMT": "044",
  "JFF": "045",
  "JBE": "046",
  "KNX": "047",
  "LAL": "048",
  "LDN": "049",
  "LNS": "050",
  "LCE": "051",
  "LVC": "052",
  "LVX": "053",
  "LBN": "054",
  "MPC": "055",
  "MPA": "056",
  "MLS": "057",
  "MSR": "058",
  "MVO": "059",
  "MHL": "060",
  "MUO": "061",
  "MNA": "062",
  "MSA": "063",
  "MCO": "064",
  "MTC": "065",
  "NAE": "066",
  "NOL": "067",
  "OTL": "068",
  "ORN": "069",
  "PDV": "070",
  "PEL": "071",
  "PAS": "072",
  "PSA": "073",
  "PTN": "076",
  "PMT": "077",
  "POP": "078",
  "POM": "079",
  "PTY": "080",
  "QXL": "081",
  "RCO": "082",
  "RFX": "083",
  "RMT": "084",
  "RXN": "085",
  "RMC": "086",
  "RAO": "087",
  "RIZ": "088",
  "RFS": "089",
  "SRO": "090",
  "SAO": "091",
  "SJE": "092",
  "SKE": "093",
  "SPE": "095",
  "SGA": "096",
  "SLO": "097",
  "SOY": "098",
  "SRS": "241",
  "TAT": "100",
  "TMR": "101",
  "TBS": "102",
  "TKB": "103",
  "TER": "104",
  "TNE": "105",
  "TED": "106",
  "TUI": "107",
  "UVE": "109",
  "VNS": "110",
  "VNX": "111",
  "VCS": "112",
  "WDL": "113",
  "IEX": "114",
  "MIT": "115",
  "SLN": "116",
  "PYA": "117",
  "WED": "118",
  "DUY": "119",
  "CRN": "120",
  "BEA": "121",
  "ALO": "122",
  "TWN": "123",
  "DFO": "124",
  "MGA": "125",
  "AOE": "126",
  "OPS": "127",
  "VGA": "128",
  "STX": "129",
  "AGA": "130",
  "TBT": "133",
  "SFR": "134",
  "BCE": "135",
  "LGE": "137",
  "YKK": "138",
  "WPP": "139",
  "CTO": "141",
  "LIN": "142",
  "GAE": "143",
  "BWT": "144",
  "FMT": "145",
  "CSE": "146",
  "MTK": "148",
  "AWL": "149",
  "DMI": "151",
  "HZT": "152",
  "LSG": "153",
  "ULE": "154",
  "ALN": "155",
  "MLF": "157",
  "ETR": "158",
  "HRL": "159",
  "NTE": "160",
  "RAL": "161",
  "DKI": "162",
  "MLX": "163",
  "FZE": "164",
  "HDT": "165",
  "CAM": "166",
  "TCA": "167",
  "BLM": "168",
  "ACC": "169",
  "DTE": "170",
  "SOT": "171",
  "KQS": "172",
  "DRI": "173",
  "FLS": "174",
  "NES": "175",
  "TBI": "176",
  "PAO": "177",
  "AES": "178",
  "CMS": "179",
  "FRA": "180",
  "PRM": "182",
  "NPC": "183",
  "UVL": "184",
  "PFO": "185",
  "WMS": "186",
  "BVS": "187",
  "HNU": "188",
  "VPO": "189",
  "CAX": "190",
  "CRE": "191",
  "NWT": "192",
  "DBL": "193",
  "PSR": "194",
  "SPS": "195",
  "PCS": "196",
  "MES": "198",
  "SII": "199",
  "SRN": "200",
  "DRT": "202",
  "GIN": "203",
  "CRS": "204",
  "AEA": "205",
  "MTR": "206",
  "AQP": "207",
  "OJN": "208",
  "LRA": "209",
  "EPN": "210",
  "BDZ": "211",
  "GJO": "212",
  "DKR": "213",
  "ORY": "214",
  "SYD": "215",
  "VDE": "216",
  "BML": "217",
  "TVO": "218",
  "RJR": "219",
  "AMI": "221",
  "TCN": "222",
  "ACT": "223",
  "RTL": "224",
  "MDA": "225",
  "SNO": "226",
  "LGS": "227",
  "APL": "228",
  "CMO": "229",
  "JGB": "230",
  "NTA": "231",
  "MRL": "233",
  "TNT": "234",
  "THR": "235",
  "MRC": "236",
  "MTS": "237",
  "TPL": "238",
  "APA": "240",
  "PCA": "242",
  "BZA": "244",
  "RTN": "245",
  "MXC": "246",
  "ISA": "247",
  "HOS": "248",
  "STN": "249",
  "MEX": "250",
  "DGR": "251",
  "PNO": "252",
  "PEG": "253",
  "MRN": "254",
  "PMX": "255",
  "NTO": "256",
  "POA": "257",
  "TNG": "258",
  "BOA": "259",
  "JDA": "260",
  "MPT": "261",
  "HRN": "262",
  "ADA": "263",
  "SUS": "264",
  "BUN": "265",
  "SGM": "266",
  "KDE": "267",
  "SLS": "268",
  "PLS": "269",
  "FNK": "270",
  "BRL": "271",
  "BLE": "272",
  "PKR": "273",
  "NTH": "274",
  "LFO": "275",
  "PTH": "276",
  "GTL": "277",
  "UFE": "278",
  "LSE": "279",
  "HMX": "280",
  "AMO": "281",
  "ARO": "282",
  "VPL": "283",
  "SRL": "284",
  "SQS": "285",
  "WTE": "286",
  "DMS": "287",
  "TSK": "288",
  "ESB": "289",
  "CQA": "290",
  "GRY": "291",
  "IFS": "292",
  "FCE": "293",
  "IML": "294",
  "DVN": "295",
  "MRY": "296",
  "SRT": "297",
  "DCO": "298",
  "RBB": "299",
  "TPR": "300",
  "ATQ": "301",
  "GDE": "302",
  "ACR": "303",
  "GOR": "304",
  "XRX": "305",
  "ENT": "306",
  "EBF": "308",
  "AVY": "309",
  "BNI": "310",
  "LMA": "311",
  "AZA": "312",
  "SMP": "313",
  "JRG": "591",
  "SCA": "315",
  "PTL": "316",
  "MCY": "317",
  "LDE": "318",
  "AZR": "319",
  "ORS": "320",
  "PNE": "321",
  "LGA": "322",
  "OBT": "323",
  "KCS": "324",
  "SPX": "325",
  "ERX": "326",
  "TLG": "327",
  "APX": "328",
  "NRN": "329",
  "PTA": "330",
  "DRK": "331",
  "VLK": "332",
  "CPG": "333",
  "MCE": "334",
  "RCI": "335",
  "BIX": "336",
  "IRS": "337",
  "ZBA": "339",
  "BGL": "341",
  "BMN": "342",
  "SRX": "343",
  "CEC": "344",
  "CRO": "345",
  "SVR": "346",
  "FOX": "347",
  "VPA": "348",
  "OKO": "349",
  "LDP": "350",
  "ULI": "351",
  "MTI": "352",
  "PTE": "353",
  "HNL": "354",
  "SNT": "355",
  "IPT": "356",
  "VLN": "357",
  "WDR": "358",
  "SGG": "359",
  "EBC": "360",
  "FMA": "361",
  "RNO": "362",
  "MRA": "363",
  "VQY": "364",
  "APR": "365",
  "RSA": "366",
  "LOS": "367",
  "MRE": "368",
  "HLS": "369",
  "CLS": "370",
  "SFK": "371",
  "GTS": "372",
  "AIO": "373",
  "VAS": "374",
  "FAX": "375",
  "WLY": "376",
  "FXE": "377",
  "TLA": "378",
  "JXS": "379",
  "HDL": "380",
  "LGR": "382",
  "LNE": "383",
  "RMS": "384",
  "ATA": "385",
  "SDS": "386",
  "BNX": "387",
  "JZO": "388",
  "PSG": "512",
  "NXS": "390",
  "AFS": "391",
  "SJT": "392",
  "SES": "393",
  "PES": "532",
  "EFE": "394",
  "MNU": "395",
  "SYM": "396",
  "ISC": "397",
  "ACO": "398",
  "MSO": "399",
  "SER": "400",
  "OPA": "401",
  "SCO": "402",
  "ANS": "403",
  "PCN": "404",
  "IPO": "405",
  "CMF": "406",
  "MRM": "407",
  "MIR": "408",
  "FDE": "409",
  "VCA": "410",
  "SPN": "411",
  "MST": "412",
  "MHI": "413",
  "SDM": "414",
  "ASW": "415",
  "BTR": "416",
  "DNI": "417",
  "NKE": "418",
  "FDL": "419",
  "PCO": "420",
  "USE": "421",
  "GSK": "422",
  "HRK": "423",
  "TOT": "424",
  "2JJ": "425",
  "KEY": "426",
  "TLR": "427",
  "UBL": "428",
  "LRP": "429",
  "CAI": "430",
  "RTP": "431",
  "nan": "669",
  "ODL": "433",
  "CAS": "434",
  "BMS": "435",
  "HLK": "436",
  "PCR": "437",
  "ECE": "438",
  "PSL": "439",
  "EQE": "440",
  "UCB": "441",
  "IXN": "442",
  "MIA": "443",
  "UNT": "444",
  "MTA": "445",
  "WNO": "446",
  "APS": "447",
  "LRL": "448",
  "MZA": "449",
  "BAY": "450",
  "SPC": "451",
  "SBR": "452",
  "PFE": "453",
  "APT": "454",
  "ATX": "455",
  "PMO": "456",
  "TBH": "457",
  "BSS": "458",
  "VIC": "459",
  "GSO": "460",
  "DLE": "461",
  "QET": "462",
  "GLN": "463",
  "TSI": "464",
  "SDE": "465",
  "KXT": "466",
  "PMG": "467",
  "KNT": "468",
  "MCA": "471",
  "DZO": "473",
  "VII": "475",
  "PLC": "476",
  "IBZ": "477",
  "MHO": "478",
  "BGN": "479",
  "BLN": "481",
  "APF": "482",
  "PRL": "483",
  "DIB": "485",
  "SFL": "488",
  "EPS": "490",
  "ADM": "484",
  "ERM": "496",
  "ASO": "497",
  "PVX": "498",
  "DTP": "499",
  "MGS": "500",
  "HSO": "501",
  "BRO": "502",
  "HNS": "503",
  "DPI": "504",
  "BVO": "505",
  "LBA": "506",
  "IDA": "507",
  "DXR": "508",
  "FVS": "509",
  "CYN": "510",
  "TLS": "511",
  "CDI": "513",
  "CER": "514",
  "BIL": "516",
  "MIL": "517",
  "TNO": "518",
  "ABL": "519",
  "KLA": "520",
  "SLE": "521",
  "CBU": "522",
  "WKO": "523",
  "SAX": "524",
  "KSG": "525",
  "BAP": "527",
  "ECL": "528",
  "SMS": "529",
  "SVO": "530",
  "ITN": "531",
  "TIM": "533",
  "PCD": "534",
  "MXT": "535",
  "HPP": "536",
  "BCR": "537",
  "NEO": "538",
  "RGR": "539",
  "MOT": "540",
  "DEL": "541",
  "RPT": "542",
  "ATK": "543",
  "PTK": "544",
  "ADN": "545",
  "NHN": "546",
  "VLS": "547",
  "BWS": "548",
  "ZQZ": "549",
  "WNN": "550",
  "QTX": "551",
  "BSN": "552",
  "VLE": "553",
  "ALA": "554",
  "MXS": "555",
  "ZBL": "556",
  "BSY": "557",
  "ZNL": "558",
  "FNR": "559",
  "DSN": "560",
  "RVD": "562",
  "TODA": "563",
  "MSC": "564",
  "ARA": "565",
  "JRC": "566",
  "IMR": "567",
  "PZL": "568",
  "LVL": "569",
  "NTX": "570",
  "IAK": "571",
  "PAZ": "572",
  "LXA": "573",
  "SRY": "574",
  "MAS": "575",
  "MNO": "576",
  "CTI": "577",
  "IDI": "578",
  "WCA": "579",
  "SWS": "580",
  "RGL": "581",
  "LBS": "582",
  "CLI": "583",
  "CTS": "584",
  "BFX": "585",
  "ABN": "586",
  "SKO": "587",
  "MBL": "588",
  "BDA": "589",
  "STE": "590",
  "CDA": "592",
  "BUC": "593",
  "ICO": "594",
  "LSI": "595",
  "PLR": "596",
  "RSG": "597",
  "MQP": "598",
  "FCV": "599",
  "ELE": "600",
  "GPS": "601",
  "QFX": "602",
  "RKO": "603",
  "ATO": "604",
  "WTL": "605",
  "BAO": "606",
  "X55": "607",
  "DAS": "608",
  "ATS": "609",
  "ETC": "610",
  "TGT": "611",
  "IND": "612",
  "TYO": "613",
  "HXR": "614",
  "BRG": "615",
  "NTN": "616",
  "PNT": "617",
  "TLE": "618",
  "GMA": "619",
  "MLE": "620",
  "DTS": "621",
  "LVQ": "622",
  "SVE": "623",
  "RVY": "625",
  "MAO": "626",
  "WVN": "627",
  "ABA": "007",
  "BKA": "628",
  "ELS": "629",
  "PDR": "630",
  "AUS": "631",
  "NSR": "632",
  "ALG": "633",
  "ETL": "634",
  "BSO": "635",
  "PTS": "636",
  "IEI": "637",
  "ESL": "638",
  "OAO": "639",
  "PTC": "640",
  "DTY": "641",
  "VCN": "642",
  "DDO": "002",
  "AJO": "003",
  "TJS": "004",
  "UMR": "643",
  "ABV": "644",
  "ESG": "645",
  "UPG": "646",
  "VTE": "647",
  "EFK": "648",
  "PVT": "649",
  "THL": "650",
  "NRA": "651",
  "UPS": "652",
  "BCA": "653",
  "KDH": "654",
  "RNA": "655",
  "VDR": "656",
  "ULS": "657",
  "PNA": "658",
  "POJ": "659",
  "LYN": "660",
  "INT": "661",
  "SAS": "670",
  "BPT": "671",
  "CUS": "672",
  "OML": "673",
  "CNR": "674",
  "SUR": "675",
  "UTE": "676",
  "GNA": "677",
  "TUS": "678",
  "RKT": "679",
  "KPO": "680",
  "PDC": "681",
  "SLX": "682",
  "JES": "683",
  "ZML": "684",
  "MSL": "685",
  "DCN": "686",
  "GLS": "687",
  "GUN": "688",
  "UTB": "689",
  "KCC": "690",
  "GOD": "691",
  "ISY": "692",
  "ASG": "693",
  "EMS": "694",
  "KSN": "695",
  "DMO": "696",
  "VUS": "697",
  "PFX": "698",
  "MGO": "699",
  "MLA": "700",
  "CVO": "701",
  "QKS": "702",
  "RCA": "703",
  "TCM": "704",
  "SFX": "705",
  "LAN": "706",
  "EPO": "707",
  "CCM": "708",
  "QLG": "709",
  "PAN": "710",
  "DFR": "711",
  "SVQ": "712",
  "PSO": "713",
  "PIM": "714",
  "GNS": "715",
  "IOL": "716",
  "CPE": "717",
  "PFR": "718",
  "VSL": "719",
  "SEI": "720",
  "BTM": "721",
  "TTL": "722",
  "GMS": "723",
  "SIR": "724",
  "DMM": "725",
  "SGS": "726",
  "RMO": "727",
  "CMR": "728",
  "EAB": "729",
  "IRL": "730",
  "JDX": "731",
  "SYO": "732",
  "WSO": "733",
  "VSP": "734",
  "CIL": "735",
  "CLT": "736",
  "ALS": "737",
  "BLS": "738",
  "SVG": "739",
  "ALL": "740",
  "CLV": "741",
  "GDX": "742",
  "WRT": "743",
  "FEE": "744",
  "BPK": "745",
  "FTX": "746",
  "KBL": "747",
  "GCA": "748",
  "JPP": "749",
  "DDK": "750",
  "CUF": "751",
  "UFX": "752",
  "LTT": "753",
  "DUH": "754",
  "ITG": "755",
  "LNL": "756",
  "IBT": "757",
  "DCE": "758",
  "DLO": "759",
  "FIP": "760",
  "CFL": "761",
  "DGS": "762",
  "IVC": "763",
  "HLI": "764",
  "BKS": "765",
  "LTA": "766",
  "KOC": "767",
  "IDT": "768",
  "CNM": "769",
  "ITT": "770",
  "RRA": "771",
  "JPS": "772",
  "ACS": "773",
  "EUE": "774",
  "MTX": "775",
  "MSX": "776",
  "PPS": "777",
  "EAS": "778",
  "HPB": "779",
  "WAR": "780",
  "PCE": "781",
  "BNZ": "782",
  "GVS": "783",
  "PDO": "784",
  "RPO": "785",
  "VLR": "786",
  "EPE": "787",
  "SIA": "788",
  "MVE": "789",
  "MEA": "790",
  "STS": "791",
  "SLC": "792",
  "PML": "793",
  "TGE": "794",
  "PSC": "795",
  "SMFF": "796",
  "MDB": "797",
  "TMA": "798",
  "WIL": "799",
  "ATT": "800",
  "GNX": "801",
  "AOS": "802",
  "BOE": "803",
  "POG": "804",
  "ZTI": "805",
  "PTQ": "806",
  "PIR": "807",
  "PJO": "808",
  "RBO": "809",
  "WPS": "810",
  "SVS": "811",
  "NSS": "812",
  "TKL": "813",
  "FLF": "814",
  "VLP": "815",
  "BXS": "816",
  "AHF": "817",
  "FRI": "818",
  "CTB": "819",
  "SVA": "820",
  "CSL": "821",
  "HLO": "822",
  "RSL": "823",
  "ITS": "824",
  "BFT": "825",
  "TKN": "826",
  "BNR": "827",
  "M3C": "828",
  "EMX": "829",
  "SQA": "830",
  "IRU": "831",
  "CPC": "832",
  "STT": "833",
  "PRA": "834",
  "SHP": "835",
  "LPT": "836",
  "YCS": "837",
  "DDA": "838",
  "CUA": "839",
  "EXE": "840",
  "SYE": "841",
  "CCE": "842",
  "SOP": "843",
  "KGT": "844",
  "SST": "845",
  "NAS": "846",
  "ACA": "847",
  "CIS": "848",
  "REG": "849",
  "FLE": "850",
  "CSG": "851",
  "IBR": "852",
  "SMO": "853",
  "NTG": "854",
  "ITA": "855",
  "SAF": "856",
  "AJA": "857",
  "HAR": "858",
  "KPS": "859",
  "JCC": "860",
  "ALP": "861",
  "ERC": "862",
  "AFE": "863",
  "NMN": "864",
  "SCN": "865",
  "NTF": "866",
  "SBT": "867",
  "CMX": "868",
  "GMC": "869",
  "CMV ": "870",
  "LBK ": "871",
  "CTA": "872",
  "DGC ": "873",
  "DVK": "874",
  "FEN": "875",
  "ARC": "876",
  "FNT": "877",
  "CMD": "878",
  "IDS": "879",
  "MTV": "880",
  "TLB": "881",
  "JDL": "882",
  "ANI": "883",
  "SPI": "884",
  "SGN": "885",
  "CAL": "886",
  "DIS": "887",
  "FTL": "888",
  "GLM": "889",
  "ART": "890",
  "MCR": "891",
  "TSF": "892",
  "ITM": "893",
  "NNO": "894",
  "EBA": "895",
  "CTX": "896",
  "WKS": "897",
  "EST": "898",
  "AGM": "899",
  "HXP": "900",
  "MFX": "901"
};
const MARCAS_NOMES = {
  "MMM": "3M",
  "AFX": "AFLEX",
  "ASY": "AIRSAFETY",
  "ARS": "ALPARGATAS",
  "ASL": "ANSELLEDMONT",
  "BBS": "B&S",
  "BLA": "BALASKA",
  "BAL": "BRACOL",
  "BDI": "BRANDASSI",
  "BSA": "BRASCOLA",
  "BLD": "BULLARD",
  "CLR": "CALMAR",
  "CGE": "CARBOGRAFITE",
  "CRL": "CARFIL",
  "CEN": "CEDON",
  "CIA": "CIPA",
  "CFO": "CONFORTO",
  "CNX": "CONNEX",
  "DAY": "DANNY",
  "DOG": "DOWCORNING",
  "DAR": "DRAGER",
  "DPT": "DUPONT",
  "DVS": "DURAVEIS",
  "ERF": "EARMUFF",
  "RCE": "ECR",
  "FAZ": "FSANTOS",
  "FZA": "FILIZOLA",
  "FAO": "FITACABO",
  "FFX": "FIXOFLEX",
  "FNA": "FRANCA",
  "FIA": "FUJIWARA",
  "HCS": "HERCULES",
  "IDL": "IDEAL",
  "IDE": "IDEALWORK",
  "ILS": "INTERLUVAS",
  "IFY": "IRISSAFETY",
  "INE": "IRONCASE",
  "IAR": "ISAMAR",
  "ITP": "ITAP",
  "JMT": "JBIMPORT",
  "JFF": "JF",
  "JBE": "JOBLUVE",
  "KNX": "KANAFLEX",
  "LAL": "LEAL",
  "LDN": "LEDAN",
  "LNS": "LINCES",
  "LCE": "LOCTITE",
  "LVC": "LUVAMAC",
  "LVX": "LUVEX",
  "LBN": "LUVIBRAN",
  "MPC": "MACPLASTIC",
  "MPA": "MAPA",
  "MLS": "MARLUVAS",
  "MSR": "MASTER",
  "MVO": "MAVARO",
  "MHL": "MECHANICAL",
  "MUO": "MERCURIO",
  "MNA": "MONTANA",
  "MSA": "MSA",
  "MCO": "MUCAMBO",
  "MTC": "MULTITEC",
  "NAE": "NEADE",
  "NOL": "NOVEL",
  "OTL": "OPTREL",
  "ORN": "ORION",
  "PDV": "PEREIRADIASPEGLAV",
  "PEL": "PETZEL",
  "PAS": "PICPLASTICOS",
  "PSA": "PLASMODIA",
  "PTN": "PORTOFINO",
  "PMT": "PROMAT",
  "POP": "PROTCAP",
  "POM": "PROTIM",
  "PTY": "PROTSPRAY",
  "QXL": "QUALITEXTIL/IDEAL",
  "RCO": "RACCO",
  "RFX": "REALFLEX",
  "RMT": "RESMAT",
  "RXN": "REXON",
  "RMC": "RIMPAC",
  "RAO": "RIOJANEIRO",
  "RIZ": "RITZ",
  "RFS": "RMDEFREITAS",
  "SRO": "SANREMO",
  "SAO": "SANRO",
  "SJE": "SAOJOSE",
  "SKE": "SEIKE",
  "SPE": "SERELEPE",
  "SGA": "SIGLA",
  "SLO": "SILO",
  "SOY": "SONY",
  "SRS": "SOCORROEPI' S",
  "TAT": "TEADIT",
  "TMR": "TECMATER",
  "TBS": "TIMBIRAS",
  "TKB": "TKVB",
  "TER": "TORAME",
  "TNE": "TORNIERE",
  "TED": "TREEBOND",
  "TUI": "TSUZUKI",
  "UVE": "UVEX",
  "VNS": "VENUS",
  "VNX": "VINITEX",
  "VCS": "VULCABRAS",
  "WDL": "WELDSTEEL",
  "IEX": "IDEATEX",
  "MIT": "MULTIPLAST",
  "SLN": "SELEON",
  "PYA": "POLYCAPA",
  "WED": "WIELAND",
  "DUY": "DULLY",
  "CRN": "CARAN",
  "BEA": "BERA",
  "ALO": "ALLEGRO",
  "TWN": "TAIWAN",
  "DFO": "DIFCO",
  "MGA": "MAGMA",
  "AOE": "ARCOVERDE",
  "OPS": "OLIMPIADAS",
  "VGA": "VANGUARDA",
  "STX": "SILALTEX",
  "AGA": "AGENA",
  "TBT": "TUBOART",
  "SFR": "SAFIR",
  "BCE": "BLUECARE",
  "LGE": "LANGONE",
  "YKK": "YKK",
  "WPP": "WPP",
  "CTO": "CENTROOTICO",
  "LIN": "LION",
  "GAE": "GLOBALFIRE",
  "BWT": "BWTECHNOLOGIES",
  "FMT": "FRIOMAT",
  "CSE": "COATS/CORRENTE",
  "MTK": "MULTSTOCK",
  "AWL": "AVLISHAWSDOBRASIL",
  "DMI": "DALMOLAI",
  "HZT": "HUZIMET",
  "LSG": "LUVASYELING",
  "ULE": "UNILINE",
  "ALN": "ACRILON",
  "MLF": "MALUF",
  "ETR": "ELASTOBOR",
  "HRL": "HORNELL",
  "NTE": "NORTENE",
  "RAL": "REAL",
  "DKI": "DENKI",
  "MLX": "MOLDEX",
  "FZE": "FIRIZZOLE",
  "HDT": "HOWARD LEIGHT",
  "CAM": "CARTOM",
  "TCA": "TOPCARGA",
  "BLM": "BELEM",
  "ACC": "ALLTEC",
  "DTE": "DANTELLE",
  "SOT": "SCOTT",
  "KQS": "KALIPSOEQUIPAMENTOS",
  "DRI": "DEPARELLI",
  "FLS": "FENALUVAS",
  "NES": "NILTONEQUIPAMENTOS",
  "TBI": "TIBAGI",
  "PAO": "PERSONAL",
  "AES": "ARTERIS",
  "CMS": "COMLUVAS",
  "FRA": "FIORELA",
  "PRM": "POWERSPAM",
  "NPC": "NEOPLASTIC",
  "UVL": "UNIVERSAL",
  "PFO": "PORTOFINO",
  "WMS": "WHITEMARTINS",
  "BVS": "BRVIDROS",
  "HNU": "HENLAU",
  "VPO": "VILLEPROTECÄO",
  "CAX": "CIPATEX",
  "CRE": "CORRENTE",
  "NWT": "NEWLIFT",
  "DBL": "DAYBRASIL",
  "PSR": "PROSIBOR",
  "SPS": "SPEQUIPAMENTOS",
  "PCS": "PICS",
  "MES": "MARTINS&SA",
  "SII": "SI",
  "SRN": "SPARTAN",
  "DRT": "DETROIT",
  "GIN": "GULLIN",
  "CRS": "CIRRUS",
  "AEA": "ALFA EBETA",
  "MTR": "MARTOR",
  "AQP": "AEROQUIP",
  "OJN": "OSJUAN",
  "LRA": "LAGROTTA",
  "EPN": "EPICON",
  "BDZ": "BACOUDALLOZ",
  "GJO": "GOJO",
  "DKR": "DOMNICKHUNTER",
  "ORY": "OUTDOORSUPPLY",
  "SYD": "SAFETYLAND",
  "VDE": "VEDERE",
  "BML": "BOMPEL",
  "TVO": "TREVO",
  "RJR": "ROJAR",
  "AMI": "ARMATI",
  "TCN": "TRANCHAN",
  "ACT": "ASCOT",
  "RTL": "ROTCEL",
  "MDA": "MERCADOTICA",
  "SNO": "SANSIRO",
  "LGS": "LEMOS&GONCALVES",
  "APL": "ACEPIL",
  "CMO": "CAMPRO",
  "JGB": "JGB",
  "NTA": "NAUTIKA",
  "MRL": "MAXXIROYAL",
  "TNT": "TRANSPLAST",
  "THR": "THR",
  "MRC": "MENORTEC",
  "MTS": "MOURAMATTOS",
  "TPL": "TROPICAL",
  "APA": "ALPINA",
  "PCA": "PLASTICOSPARANA",
  "BZA": "BOZZA",
  "RTN": "RONTAN",
  "MXC": "MAXPLAC",
  "ISA": "IRMAOSHAGA",
  "HOS": "HIDROPARTS",
  "STN": "SETON",
  "MEX": "MADEITEX",
  "DGR": "DIGITADOR",
  "PNO": "PLANETASINALIZACAO",
  "PEG": "PROSEG",
  "MRN": "MELO&ROZIN",
  "PMX": "PROMAX",
  "NTO": "NITO",
  "POA": "PROCIPA",
  "TNG": "TECNOSEG",
  "BOA": "BELLOTA",
  "JDA": "JSINDUSTRIA",
  "MPT": "MANUPLAST",
  "HRN": "HELLERMANN",
  "ADA": "ANADONA",
  "SUS": "SUSA",
  "BUN": "BRUNAN",
  "SGM": "SPRAYINGSYSTEM",
  "KDE": "KIDDE",
  "SLS": "SOLS/A",
  "PLS": "PROLUVAS",
  "FNK": "FORNEMAK",
  "BRL": "BORCOL",
  "BLE": "BRASILULTRAFORTE",
  "PKR": "PARKER",
  "NTH": "NORTH",
  "LFO": "LUIZFRANCISCO",
  "PTH": "PROTECH",
  "GTL": "GREATWALL",
  "UFE": "ULTRAFORTE",
  "LSE": "LUVASSETE",
  "HMX": "HIMAFLEX",
  "AMO": "ANTONIOMARCELO",
  "ARO": "ARROYO",
  "VPL": "VIPAL",
  "SRL": "SAORAFAEL",
  "SQS": "SOLUCAOEQUIPAMENTOS",
  "WTE": "WHITELAKE",
  "DMS": "DERMAPLUS",
  "TSK": "TASK",
  "ESB": "ECOSORB",
  "CQA": "CONQUISTA",
  "GRY": "GUARANY",
  "IFS": "INTERFILTROS",
  "FCE": "FUNDACAORIODOCE",
  "IML": "INDEMETAL",
  "DVN": "DEVCON",
  "MRY": "MARKEY",
  "SRT": "STARRETT",
  "DCO": "DUCOURO",
  "RBB": "R&B",
  "TPR": "TOPLEATHER",
  "ATQ": "ATAQ",
  "GDE": "GRENDENE",
  "ACR": "ACR",
  "GOR": "GOODYER",
  "XRX": "XEROX",
  "ENT": "EQUINAUT",
  "EBF": "EBF",
  "AVY": "AVERY",
  "BNI": "BIANCHI",
  "LMA": "LUMICA",
  "AZA": "ARIZONA",
  "SMP": "SERMAP",
  "JRG": "JMARSEG",
  "SCA": "STRACTA",
  "PTL": "PONTUAL",
  "MCY": "MERCURY",
  "LDE": "LUVASDOVALE",
  "AZR": "AZR",
  "ORS": "ORUS",
  "PNE": "PROTENORTE",
  "LGA": "LALIZASS.A-GRECIA",
  "OBT": "OPTIBELT",
  "KCS": "KIM´SCOUROS",
  "SPX": "SUPERMAX",
  "ERX": "EVERLUX",
  "TLG": "TRELLEBORG",
  "APX": "ARPREX",
  "NRN": "NURION",
  "PTA": "PERFITECNICA",
  "DRK": "DESCARPACK",
  "VLK": "VOLK",
  "CPG": "CAPSEG",
  "MCE": "MERCOFIRE",
  "RCI": "R.CHESINI",
  "BIX": "BLINDEX",
  "IRS": "INTERMAS",
  "ZBA": "ZEBRA",
  "BGL": "BERG-STEEL",
  "BMN": "BILSOMSPERIAN",
  "SRX": "SORBEX",
  "CEC": "CIEC",
  "CRO": "CHAPEUSRIOBRANCO",
  "SVR": "SURVIVAR",
  "FOX": "FOX",
  "VPA": "VIPOSA",
  "OKO": "OKUBO",
  "LDP": "LEADERSHIP",
  "ULI": "UNILOGI",
  "MTI": "MUSITANI",
  "PTE": "PROTENGE",
  "HNL": "HENKEL",
  "SNT": "SINART",
  "IPT": "IDAPLAST",
  "VLN": "VULCAN",
  "WDR": "WORLDCENTER",
  "SGG": "SG",
  "EBC": "EMBRAMAC",
  "FMA": "FAMA",
  "RNO": "RENOVO",
  "MRA": "MARAGNA",
  "VQY": "VEDAQUALITY",
  "APR": "ALPHALIDER",
  "RSA": "RESANA",
  "LOS": "LEETOOLS",
  "MRE": "MARFE",
  "HLS": "HONEYWELLANALYTICS",
  "CLS": "CRALVES",
  "SFK": "SAFETAK",
  "GTS": "GATES",
  "AIO": "AIRMICRO",
  "VAS": "VEDABRAS",
  "FAX": "FLAX",
  "WLY": "WILLY",
  "FXE": "FLEXFORTE",
  "TLA": "TRILONA",
  "JXS": "JUNDEXTINTORES",
  "HDL": "HDL",
  "LGR": "LEMGRUBER",
  "LNE": "LONALEVE",
  "RMS": "RIOSEMARES",
  "ATA": "ATIVA",
  "SDS": "SKYDESCARTAVEIS",
  "BNX": "BANTEX",
  "JZO": "JARIZZO",
  "PSG": "PLASTSEG",
  "NXS": "NEXUS",
  "AFS": "ABVFERNANDES",
  "SJT": "STELLJOINT",
  "SES": "SES",
  "PES": "PROJETOS&SERVIÇOS",
  "EFE": "EDUFORME",
  "MNU": "MANASLU",
  "SYM": "SUNSYSTHEM",
  "ISC": "ISC",
  "ACO": "AAROCOMERCIO",
  "MSO": "MACASMELLO",
  "SER": "SENSEAR",
  "OPA": "ORTOPRATIKA",
  "SCO": "SCUDO",
  "ANS": "ATLANTIS",
  "PCN": "PELICAN",
  "IPO": "IGAPOO",
  "CMF": "CIMAF",
  "MRM": "MIRIM",
  "MIR": "MARIMAR",
  "FDE": "FUNDIVE",
  "VCA": "VECTRA",
  "SPN": "SPERIAN",
  "MST": "MULTSPLINT",
  "MHI": "MALHARIANAPOLI",
  "SDM": "SUNDSTROM",
  "ASW": "ASW",
  "BTR": "BRIGTHSTAR",
  "DNI": "DNI",
  "NKE": "NIKE",
  "FDL": "FIODELL",
  "PCO": "PROINCENDIO",
  "USE": "ULTRASAFE",
  "GSK": "GKGLASSBEK",
  "HRK": "HARVIK",
  "TOT": "TUBOLIT",
  "2JJ": "2AJ",
  "KEY": "KAEFY",
  "TLR": "TERMOLAR",
  "UBL": "UNIBRASIL",
  "LRP": "LEROUP",
  "CAI": "COMERCIALBERENELI",
  "RTP": "REMATIPTOP",
  "nan": "nan",
  "ODL": "OMBDOBRASIL",
  "CAS": "COMMANDERS",
  "BMS": "BOMBEIROS",
  "HLK": "HOLIK",
  "PCR": "PLASTCOR",
  "ECE": "ETCHE",
  "PSL": "PROTSINAL",
  "EQE": "ENFOQUE",
  "UCB": "USCLIMB",
  "IXN": "IXON",
  "MIA": "M.C.INDUSTRIA",
  "UNT": "UNIVET",
  "MTA": "MOTOROLA",
  "WNO": "WILLIANPAULO",
  "APS": "ALPENPASS",
  "LRL": "LAERDAL",
  "MZA": "MAZOTA",
  "BAY": "BRADY",
  "SPC": "SIPEC",
  "SBR": "SBPR",
  "PFE": "PUNHOFORTE",
  "APT": "ALLPROT",
  "ATX": "ARTEFLEX",
  "PMO": "PIMACO",
  "TBH": "T-BRUSH",
  "BSS": "BRASILMINASUNIFORMES",
  "VIC": "VICSA",
  "GSO": "GIOVANNIB.SBONATTO",
  "DLE": "DILEPE",
  "QET": "QUEST",
  "GLN": "GILIAN",
  "TSI": "TSI",
  "SDE": "SENSIDYNE",
  "KXT": "KENTEXPORT",
  "PMG": "PLASTMG",
  "KNT": "KIRINPLAST",
  "MCA": "MECANICAREUNIDA",
  "DZO": "DURAZZO",
  "VII": "VI",
  "PLC": "PULTEC",
  "IBZ": "IRBOZ",
  "MHO": "MICHELINO",
  "BGN": "BERGSON",
  "BLN": "BELLKRON",
  "APF": "APF",
  "PRL": "PORTAL",
  "DIB": "DIB",
  "SFL": "SISTEMADEFLUXOBRASIL",
  "EPS": "EXPOSIS",
  "ADM": "ANDBEM",
  "ERM": "ENERCOM",
  "ASO": "ASTRO",
  "PVX": "PREVEMAX",
  "DTP": "DEUTSHLAMP",
  "MGS": "MAGICMINAS",
  "HSO": "HERCULESPROJETO",
  "BRO": "BRASMO",
  "HNS": "HANGZHOU CHINASTARS",
  "DPI": "DIPROPI",
  "BVO": "BRAVO",
  "LBA": "LINABRA",
  "IDA": "IMPORTADORAIMPEDA",
  "DXR": "DEXCAR",
  "FVS": "FIRESERVIÇOS",
  "CYN": "CROYDON",
  "TLS": "TEXTILBANDBS",
  "CDI": "CANADAEPI",
  "CER": "CREMER",
  "BIL": "BRINELL",
  "MIL": "MAICOL",
  "TNO": "TONINATO",
  "ABL": "AZBRASIL",
  "KLA": "KELTA",
  "SLE": "SEALTAPE",
  "CBU": "COBAU",
  "WKO": "WILKURO",
  "SAX": "SEALUX",
  "KSG": "KSEG",
  "BAP": "BETAEQUIP",
  "ECL": "EXCEL",
  "SMS": "SISTERMAQUINAS",
  "SVO": "SERVICO",
  "ITN": "INITRON",
  "TIM": "TIM",
  "PCD": "PAMCOLD",
  "MXT": "MAXPRINT",
  "HPP": "HP",
  "BCR": "BR COLETES REFLETIVOS ",
  "NEO": "NAOESPECIFICADO",
  "RGR": "RANGEROVER",
  "MOT": "MICROSOFT",
  "DEL": "DELL",
  "RPT": "REPTEC",
  "ATK": "ARTMEK",
  "PTK": "PACK&TRACK",
  "ADN": "ALADDIN",
  "NHN": "NEWHORIZON",
  "VLS": "VIVALDOCALCADOS",
  "BWS": "BW-Serviços",
  "ZQZ": "ZUQUIBRAZ",
  "WNN": "WESTERN",
  "QTX": "QUALITYFIX",
  "BSN": "BRASOPOLIS-EQUIPAMEN",
  "VLE": "VESTLINE",
  "ALA": "ANDRELUISDESOUZA",
  "MXS": "MAXIMINAS",
  "ZBL": "ZIEGLERDOBRASIL",
  "BSY": "BS-BRASILSAFETY",
  "ZNL": "ZANEL",
  "FNR": "FIANCOR",
  "DSN": "DAISAN",
  "RVD": "RAVID",
  "TODA": "TRINDUSTRIA",
  "MSC": "MINASPROTEC",
  "ARA": "ARAXA",
  "JRC": "JARC",
  "IMR": "IZAMAR",
  "PZL": "PETZL",
  "LVL": "LUVIPEL",
  "NTX": "NUTRIEX",
  "IAK": "IDEALWORK",
  "PAZ": "PAPAIZ",
  "LXA": "LFTEIXEIRA",
  "SRY": "SUPERSAFETY",
  "MAS": "MOAIS",
  "MNO": "MANZO",
  "CTI": "CONTRATOSEPI",
  "IDI": "INDUSTRIADECABEDAI",
  "WCA": "WEDGECALCADOSLTDA",
  "SWS": "SOFTWORKS",
  "RGL": "ROGIL",
  "LBS": "LIBUS",
  "CLI": "CASAOLIVETTI",
  "CTS": "CALFORITALBOTAS",
  "BFX": "BOXFLEX",
  "ABN": "AMBCLEAN",
  "SKO": "STOKO",
  "MBL": "MANTASBRASIL",
  "BDA": "BICHODASEDA",
  "STE": "SAFETLINE",
  "CDA": "CLAUDIAMARIA",
  "BUC": "BIRUTEC",
  "ICO": "INDUSTRIAECOMERCIO",
  "LSI": "LEOESDOEPI",
  "PLR": "POLO-AR",
  "RSG": "RESSEG",
  "MQP": "MAQUIMP",
  "FCV": "FCV",
  "ELE": "ESPACOLIVRE",
  "GPS": "GREEN PROCESS",
  "QFX": "QUALIFLEX",
  "RKO": "RASKALO (RAMEBEL)",
  "ATO": "ANTENASTRIANGULO",
  "WTL": "WETZEL",
  "BAO": "BOTINASPEAO",
  "X55": "X-5",
  "DAS": "DBI SALA",
  "ATS": "ALTISEG",
  "ETC": "EPITEC",
  "TGT": "TAGOUT",
  "IND": "IRONCLAD",
  "TYO": "TAYCO",
  "HXR": "HEXARMOR",
  "BRG": "B HERZOG",
  "NTN": "NETTEN",
  "PNT": "PANTANEIRO",
  "TLE": "TOOLSAFE",
  "GMA": "GAMILUVA",
  "MLE": "METALACRE",
  "DTS": "DELTAPLUS",
  "LVQ": "LUVEQ",
  "SVE": "SEIVE",
  "RVY": "RIO VALLEY",
  "MAO": "MW AUTOMACAO",
  "WVN": "WK VISION",
  "ABA": "ALBA",
  "BKA": "BUCKA",
  "ELS": "ELOS",
  "PDR": "PLASTIDUR",
  "AUS": "ACM UNIFORMES",
  "NSR": "NESFER",
  "ALG": "ALG",
  "ETL": "ESTIVAL",
  "BSO": "BOTAS VENTO",
  "PTS": "PROTS",
  "IEI": "CKS INCOREFRI",
  "ESL": "ECOSINAL",
  "OAO": "OLIVEIRAEAZEVEDO",
  "PTC": "PROPTIC",
  "DTY": "DYSTRAY",
  "VCN": "VALCAN",
  "DDO": "DADALTO",
  "AJO": "ANJOCOURO",
  "TJS": "TRESJCOUROS",
  "UMR": "ULTRAMASTER",
  "ABV": "ABV",
  "ESG": "EPISEG",
  "UPG": "UTILPLUG",
  "VTE": "VERTICE",
  "EFK": "EXFAK",
  "PVT": "PROVEST",
  "THL": "TECHGEL",
  "NRA": "NORMA",
  "UPS": "UNIFORMESPERFEITOS",
  "BCA": "BIG COMPRA",
  "KDH": "KADESH",
  "RNA": "RENOVA",
  "VDR": "VONDER",
  "ULS": "UNILUVAS",
  "PNA": "PIONEIRA",
  "POJ": "PROTEJ",
  "LYN": "LYNUS   ",
  "INT": "INSTRUTEMP",
  "SAS": "SUPREMALUVAS",
  "BPT": "BIOPROT",
  "CUS": "CSC UNIFORMES",
  "OML": "OMEGALUVAS",
  "CNR": "CIENCOR",
  "SUR": "SECUR",
  "UTE": "UNISETE",
  "GNA": "GENOVA",
  "TUS": "TAURUS",
  "RKT": "ROCKET",
  "KPO": "KAPPAO",
  "PDC": "PROTDESC",
  "SLX": "STEELFLEX",
  "JES": "JOGEPIS",
  "ZML": "ZAMETAL",
  "MSL": "MASEL",
  "DCN": "DICON",
  "GLS": "GIROLUVAS",
  "GUN": "GULIN",
  "UTB": "ULTRALUB",
  "KCC": "KCC",
  "GOD": "GIROLED",
  "ISY": "INNOVA SAFETY",
  "ASG": "ALSEG",
  "EMS": "EXTREMOSUL/HJS",
  "KSN": "KSN",
  "DMO": "DEJAMARO",
  "VUS": "VICTOR'S LUVAS",
  "PFX": "POLIFLEX",
  "MGO": "MGCINTO",
  "MLA": "MAZOLA",
  "CVO": "CAPASDECHUVARIBEIRAO",
  "QKS": "QUALITY KOUROS",
  "RCA": "RCA",
  "TCM": "THECOM",
  "SFX": "SAFEX",
  "LAN": "LALAN",
  "EPO": "EQPRO",
  "CCM": "CALCAR BEM",
  "QLG": "QUALISSEG",
  "PAN": "PEATON",
  "DFR": "DIAFER",
  "SVQ": "SERVEQ",
  "PSO": "PERISSATO",
  "PIM": "PERICOM",
  "GNS": "GANIRIS",
  "IOL": "INCOMPEL",
  "CPE": "CAPERE",
  "PFR": "PROTEFER",
  "VSL": "VISBEL",
  "SEI": "SAFETY EPI",
  "BTM": "BENETHERM",
  "TTL": "TECNOTEXTIL",
  "GMS": "G M COUROS",
  "SIR": "SEARIVER",
  "DMM": "DM",
  "SGS": "SECURITY GLASSES",
  "RMO": "RAMBO",
  "CMR": "CAMPER",
  "EAB": "ESAB",
  "IRL": "INSTRUSUL",
  "JDX": "JUNDTEX",
  "SYO": "SAYRO",
  "WSO": "WN SINALIZACAO",
  "VSP": "VESTI PELLI",
  "CIL": "CRIVAL",
  "CLT": "CALMART",
  "ALS": "ART'S LUVAS",
  "BLS": "BLS",
  "SVG": "SILVSEG",
  "ALL": "ALLIANCE",
  "CLV": "CLIVE",
  "GDX": "GUARDIAN DX",
  "WRT": "WURTH",
  "FEE": "FREEDOM",
  "BPK": "BOMPAK",
  "FTX": "FILTRAX",
  "KBL": "KABALLAH",
  "GCA": "GRACIA",
  "JPP": "JERSEY POMPOM",
  "DDK": "DERMAPLUS (DRAKKAR)",
  "CUF": "CLASSIC UNIFORMES",
  "UFX": "UNIFORTEX",
  "LTT": "LUTESTIL",
  "DUH": "DUH",
  "ITG": "ITIS GIRL",
  "LNL": "LUNELLI",
  "IBT": "IMBAT",
  "DCE": "DESCARTES EPI",
  "DLO": "DELLO",
  "FIP": "FIRST IMPORT",
  "CFL": "CARTA FABRIL",
  "DGS": "DGIFTS",
  "IVC": "INVICTUS",
  "HLI": "HILTI",
  "BKS": "BRASKOUROS",
  "LTA": "LANTERNA TATICA",
  "KOC": "KOCH",
  "IDT": "INDART",
  "CNM": "CHINAMAX",
  "ITT": "INSTRUTHERM",
  "RRA": "RRA",
  "JPS": "JERUEL PLASTICOS              ",
  "ACS": "ATHENAS CINTOS                ",
  "EUE": "ESCUDEIRO UNIFORMES E EPI",
  "MTX": "METALTEX",
  "MSX": "MINASFLEX",
  "PPS": "PROTEPLUS ",
  "EAS": "ESD ANTIESTATICOS",
  "HPB": "HYPERMAQ PLASTICO E BORRACHA  ",
  "WAR": "WANA WEAR                     ",
  "PCE": "PROMASTER COUROS E EPIS       ",
  "BNZ": "BUNZL ",
  "GVS": "GVS",
  "PDO": "PADO ",
  "RPO": "RS PROTECAO",
  "VLR": "VILMAR",
  "EPE": "EQUIPE ",
  "SIA": "SOGIMA ",
  "MVE": "MF ALAVARQUE ",
  "MEA": "MUNDO ERGONOMIA",
  "STS": "SPARE PARTS",
  "SLC": "SLICE ",
  "PML": "PROMETAL",
  "TGE": "TALGE",
  "PSC": "PLACAR SINALIZACAO",
  "SMFF": "SMF",
  "MDB": "MEDIX BRASIL",
  "TMA": "TIMA",
  "WIL": "WEILL",
  "ATT": "ALL PROT",
  "GNX": "GIENEX",
  "AOS": "AMERICAN ALLOYS",
  "BOE": "BLOELE",
  "POG": "PIONG",
  "ZTI": "ZATTI",
  "PTQ": "PROTEQ",
  "PIR": "POLI-FERR",
  "PJO": "PROJATO",
  "RBO": "RIO BRANCO",
  "WPS": "WP EQUIPAMENTOS",
  "SVS": "SEGLUVAS",
  "NSS": "NSS",
  "TKL": "TEKNOLUVAS",
  "FLF": "FULLSAFE",
  "VLP": "VELPER",
  "BXS": "BOXER SOLDAS",
  "AHF": "ALPHA-FER",
  "FRI": "FARIA",
  "CTB": "COTEBRAS",
  "SVA": "SILVEIRA",
  "CSL": "CSL POLARIS",
  "HLO": "HILLOS",
  "RSL": "RESIL",
  "ITS": "INTERATIVA SOLUCOES",
  "BFT": "BRASFORT",
  "TKN": "TEKIN",
  "BNR": "BONIER",
  "M3C": "CM3",
  "EMX": "EDUMAX",
  "SQA": "START QUIMICA ",
  "IRU": "IRUDEK",
  "CPC": "COMPANHIA CABOS",
  "STT": "SANTOS SAFETY",
  "PRA": "PROAUTO",
  "SHP": "SAFETECH PROTECTION           ",
  "LPT": "LUPLAST ",
  "YCS": "FLY CAPACETES",
  "DDA": "DORMED HOSPITALAR ",
  "CUA": "CURTLUVAS",
  "EXE": "EXERTEX",
  "SYE": "SAFETY GLASSES ",
  "CCE": "MCCUE",
  "SOP": "SCHIOPPA",
  "KGT": "KING TALHAS",
  "SST": "SANSEI TALHAS",
  "NAS": "NASHA",
  "ACA": "ACRO CABOS",
  "CIS": "CISER",
  "REG": "RESGATEX",
  "FLE": "FORTFLEX",
  "CSG": "CSG WORK",
  "IBR": "IBR BRASIL",
  "SMO": "MSO",
  "NTG": "NITGEN",
  "ITA": "ITACORDA",
  "SAF": "SAFETEC",
  "AJA": "AJANK",
  "HAR": "HARD",
  "KPS": "KPN SAFETY                    ",
  "JCC": "JC CALDEIRARIA",
  "ALP": "ALLTAPE",
  "ERC": "EUROCEL                       ",
  "AFE": "ABAFIRE",
  "NMN": "NMICHELIN",
  "SCN": "SELCON",
  "NTF": "NOTIFIER",
  "SBT": "SIBRATEC",
  "CMX": "CHAMATEX",
  "GMC": "GM COUROS ",
  "CMV ": "CMV",
  "LBK ": "LUBEKA",
  "CTA": "CONTROL SAFE ",
  "DGC ": "DG CINTOS ",
  "DVK": "DUVEK ",
  "FEN": "FENIOR ",
  "ARC": "ARCLAN ",
  "FNT": "FACINTOS",
  "CMD": "COSMODERMA",
  "IDS": "ID SAFETY",
  "MTV": "MASTER VISION",
  "TLB": "TELBRAS",
  "JDL": "JEDAL",
  "ANI": "ANCORA INDUSTRIAL",
  "SPI": "SUPORT INDUSTRIA",
  "SGN": "SIGNMAKER",
  "CAL": "CALBRAS",
  "DIS": "DIVISEG",
  "FTL": "FORTLINE",
  "GLM": "GLM",
  "ART": "ARTENAFEX",
  "MCR": "MCR SAFETY",
  "TSF": "TRES FORTES",
  "ITM": "INSTRUTEMP",
  "NNO": "NINO'S INDUSTRIA",
  "EBA": "EBAC",
  "CTX": "CINTAMAX",
  "WKS": "WORK SAFETY",
  "EST": "ESSENTRA",
  "AGM": "AGMOV",
  "HXP": "HEXPRO",
  "MFX": "MULTFLUXO"
};

const TIPOS_PRODUTO = {
  "ME": "MERCADORIA",
  "MP": "MATERIA PRIMA",
  "MC": "MATERIAL CONSUMO",
  "BN": "BENEFICIAMENTO",
  "OI": "OUTROS INSUMOS",
  "AI": "ATIVO IMOBILIZADO",
  "EM": "EMBALAGENS",
  "PI": "PRODUTO INTERMEDIARIO",
  "Z3R0": "NÃO LOCALIZADO",
  "RV": "REVENDA DE PRODUTOS NACIONAL E/OU IMPORTADO",
  "MO": "MAO DE OBRA",
  "MT": "MANUTENCAO DE TRAVA QUEDAS",
  "AF": "ATIVO FIXO",
  "MA": "MANUTENCAO DE ATIVOS",
  "GG": "GASTOS GERAIS",
  "SE": "NÃO LOCALIZADO",
  "MI": "MATERIAL DE INFORMATICA",
  "PA": "PRODUTO ACABADO",
  "PC": "PAGAMENTO DE CONTA",
  "DN": "DISTRIBUICAO DE PRODUTO NACIONAL",
  "PV": "PRODUTO VEICULO",
  "SP": "SUBPRODUTO"
};

const TIPOS_PREENCHIMENTO = {
  "C": "C — CALCADO, CUTTER, CADEADO",
  "D": "D — DESCARTAVEL, IMPERMEAVEL, Produtos Quimicos",
  "F": "F — CAPACETE, Capacetes, PROTECAO AUDITIVA",
  "G": "G — LUVA",
  "H": "H — CHUVEIRO E LAVA-OLHOS, PROTECAO VISUAL",
  "I": "I — BLOQUEIO, BOLSA, SINALIZACAO",
  "J": "J — PROTECAO TERMICA(CALOR,FOGO,ARCO ELETRICO)",
  "K": "K — PROTECAO TERMICA (FRIO)",
  "L": "L — ALTURA",
  "O": "O — ESPACO CONFINADO, Manutenção, Reparo e Operações"
};

const GRUPOS_NUM = {
  "ACESSORIOS": "CIK0",
  "LINHA DE VIDA HORIZONTAL": "A0F0",
  "LINHA DE VIDA VERTICAL": "A0D0",
  "MANUTENCAO": "MANU",
  "ACESSO E RESGATE": "A0E0",
  "ACESSORIOS ESPACO CONFINADO": "B4J0",
  "VENTILACAO (ESP.CONFINADO)": "1006",
  "SERVICOS DE ENGENHARIA": "A0A0",
  "MONITOR DE GAS": "B4I0",
  "TRAVA-QUEDA RETRATIL": "A0B1",
  "CALCAS": "B1B0",
  "CUTTER NIVEL 5": "B9A4",
  "ACESSORIOS CUTTER": "B9A5",
  "TRAVA-QUEDA CABO DE ACO": "A0B2",
  "INSU./EXA. AREA N CLASSIFICADA": "B4G1",
  "MANGUEIRAS": "C1E1",
  "DISPOSITIVO DE ANCORAGEM": "A0C0",
  "DUTO AREA NAO CLASSIFICADA": "B4H1",
  "ACESSORIOS COMBATE INCENDIO": "B3E0",
  "TRAVA-QUEDA CORDA": "A0B3",
  "TRIPE": "B4B0",
  "3WAY": "B4D0",
  "DIVERSO SINALIZACAO": "B5I0",
  "ADMINISTRATIVO": "ADMI",
  "CUTTER": "8000",
  "ESPACO CONFINADO": "1000",
  "ATIVO FIXO": "FIXO",
  "CADEADO": "B7B0",
  "CUTTER DESCONTINUADO": "B9A6",
  "GUINCHO": "B4C0",
  "VESTIMENTA IMPERMEAVEL": "A8A0",
  "PROJETO/ENGE. DESCONTINUADO": "SPA0",
  "LIQUIDO GERADOR DE ESPUMA LGE": "B3D3",
  "IMPERMEAVEL DESCONTINUADO": "A8E0",
  "RESPIRADOR DESCART. C/ VALVULA": "A2A0",
  "VESTIMENTA ARCO ELETRICO CAT.1": "A3A0",
  "PROTECAO QUIMICA DESCONTINUADO": "A5A4",
  "LUVA PROCEDIMENTO": "A6B1",
  "LUVA PARA RISCO MECANICO": "A6D0",
  "PALMILHAS": "0402",
  "ACESSORIOS CALCADO": "A7E0",
  "CAPACETE": "B0A0",
  "BONE CASQUETE": "B0B0",
  "CONE / BANDEIROLA SINALIZACAO": "B5B0",
  "CAVALETE/PEDESTAL SINALIZACAO": "B5C0",
  "COLETE SINALIZACAO": "B5A0",
  "BOTA PVC": "A7A0",
  "BOTA PU": "A7A3",
  "PORTA FERRAMENTA": "C0B0",
  "BOTA BORRACHA": "A7A1",
  "VESTIMENTA ARCO ELETRICO CAT.4": "A3A3",
  "BOTA VAQUETA": "A7A2",
  "SAPATO COURO": "A7D0",
  "VESTIMENTA OUTROS": "A3A7",
  "BOTINA COURO": "A7B0",
  "BOTINA PU": "A7B3",
  "DESCONTINUADO": "A7D4",
  "BOTINA NOBUCK": "A7B1",
  "COTURNO COURO": "A7F0",
  "Diversos": "0340",
  "SANDALIA NOBUCK": "A7G0",
  "MEMBROS SUPERIORES": "03",
  "TENIS PU": "A7C3",
  "BOTINA MICROFIBRA": "A7B4",
  "SAPATO MICRO FIBRA": "A7D1",
  "BONES": "B1F0",
  "OCULOS COMUNS": "A4A0",
  "CHUVEIRO": "C7A0",
  "Cutter": "B9",
  "DEMANDA DIRECIONADA": "X0X0",
  "CALCADO DESCONTINUADO": "A7F1",
  "AVENTAIS": "B1I0",
  "TENIS COURO": "A7C0",
  "VESTIMENTA PARA SOLDA": "A3A4",
  "TENIS MICRO FIBRA": "A7C1",
  "BALACLAVA COMBATE A ICENDIO": "B3A5",
  "AGENTE QUIMICO (S)-PROT. 5 E 6": "A5B0",
  "LUVA PARA RISCO QUIMICO": "A6B0",
  "DIVERSOS": "55",
  "ACESSORIOS EM GERAL": "AO00",
  "BOTINAS": "0405",
  "BOTINA BORRACHA": "A7B2",
  "BOTA EVA": "A7A4",
  "SAPATO EVA": "A7D3",
  "Fusiveis": "0410",
  "TOUCA DESCARTAVEL": "A9B0",
  "DIVERSOS DESCARTAVEL": "A9G0",
  "LUVA DIVERSOS": "A6F0",
  "SAPATILHA DESCARTAVEL": "A9D0",
  "VESTIMENTA ARCO ELETRICO CAT.2": "A3A1",
  "ACESSORIOS P/ PROTECAO FACIAL": "A4B1",
  "CREME PARA MAOS": "B2A0",
  "AGENTE QUIMICO (L/G) - PROT. 1": "A5A0",
  "ARMARIOS E ABRIGOS": "B3B4",
  "COTURNO": "0435",
  "EQUIPAMENTO AUTONOMO": "A2E0",
  "TENIS": "0415",
  "BOTAS": "0401",
  "CAMISAS": "B1A0",
  "PROTECAO A CABECA": "4600",
  "MACACOES": "B1D0",
  "VESTIMENTAS COMBATE A INCENDIO": "B3A0",
  "JAPONA PROTECAO TERMICA (FRIO)": "C6A0",
  "BLUSAO PROTECAO TERMICA (FRIO)": "C6C0",
  "AVENTAL DESCARTAVEL": "A9C0",
  "CAPUZ / TOUCA": "4605",
  "CONJUNTOS": "B1C0",
  "CAPUZES/TOUCAS": "0735",
  "PERNEIRAS": "B1H0",
  "ACESSORIOS DE BLOQUEIO": "B7E0",
  "VESTI. RESPINGO METAL FUNDIDO": "A3A5",
  "EXTINTOR": "C1D1",
  "EXTINTORES": "B3D0",
  "CAPACETES": "4601",
  "PROTETOR FACIAL SIMPLES": "A4B0",
  "ABAFADOR TIPO CONCHA DIVERSOS": "A1A0",
  "ACESSORIOS RESP. AR COMPRIMIDO": "A2C1",
  "CARTUCHO / FILTRO": "A2F0",
  "ACESSORIOS E PECAS PROT. RESP.": "A2D0",
  "PLUG DE INSERCAO": "A1B0",
  "ACESSORIOS MASCARA SOLDA": "A4C3",
  "ABAFADOR CONCHA ACOPLAVEL": "A1A2",
  "ACESSORIOS PROTECAO AUDITIVA": "A1D0",
  "RESP.  REUTIL. SEMI-FACIAL": "A2B0",
  "PROT. RESPIRAT. DESCONTINUADO": "A2B2",
  "RESPIRADOR DESCART. S/ VALVULA": "A2A1",
  "ABAFADOR CONCHA HASTE FIXA": "A1A1",
  "PROTETOR AUDITIVO ATIVO": "A1C0",
  "FITA PARA IMPRESSORA": "C5B0",
  "MASCARA DESCARTAVEL": "A9A0",
  "FITA SINALIZACAO": "B5D0",
  "RESP. REUTIL. FACIAL INTEIRA": "A2B1",
  "PROTECAO RESP. DESCONTINUADO": "A2C4",
  "CARTUCHOS/FILTRO": "0535",
  "Eletrodutos E Conexoes": "0540",
  "PROTECAO VISUAL DESCONTINUADO": "A4C5",
  "RESPIRATORIA": "05",
  "ACESSORIOS OCULOS": "A4A3",
  "CAPACETE COMBATE A ICENDIO": "B3B0",
  "ACESSORIOS RESP. MOTORIZADO": "A2C3",
  "PROT. TERMICA DESCONTINUADO": "A3H4",
  "LUVA PARA RISCO BIOLOGICO": "A6C0",
  "AGENTE QUIMICO (L/G) - PROT. 3": "A5A2",
  "PROTECAO SOLAR": "B2E0",
  "DOSADOR": "B2F0",
  "AGENTE QUIMICO (L/G) - PROT. 4": "A5A3",
  "LUVA PARA RISCO TERMICO": "A6A0",
  "TENIS NOBUCK": "A7C2",
  "MANGOTES/MANGAS": "0395",
  "Luvas": "A6",
  "Madeira E Derivados": "0820",
  "LUVAS ALGODAO/FIOS SINTETICOS": "0335",
  "VESTIMENTA PROTECAO MECANICA": "A3A6",
  "MANGOTE DESCARTAVEL": "A9F0",
  "Impermeavel": "A8",
  "CAPA 7/8 PROT. TERMICA (FRIO)": "C6D0",
  "COLETES": "2010",
  "JARDINEIRAS": "B1E0",
  "ACESSORIOS PROT. TERMICA(FRIO)": "C6F0",
  "LUVA DESCONTINUADO": "A6A9",
  "SANDALIA COURO": "A7G1",
  "CREMES DE PROTECAO": "4700",
  "SABONETE EM GERAL": "B2D0",
  "REPELENTE": "B2C1",
  "SEMI-FACIAL": "0505",
  "MASCARA DE SOLDA SIMPLES": "A4C0",
  "CINTURAO ABDOMINAL": "A0A2",
  "DETECTOR DE GASES": "4010",
  "ABAFADOR CONCHA HASTE NA NUCA": "A1A3",
  "MASCARA SOLDA ESCURECIME. AUT.": "A4C1",
  "VALVULA DE BLOQUEIO": "B7A0",
  "OCULOS AMPLA VISAO": "A4A1",
  "MASCARAS SOLDADORES": "4604",
  "CHUVEIRO LAVA-OLHOS": "C7B0",
  "MACAS": "C8A0",
  "DETECTORES DE FUMACA": "B3D2",
  "CADEIRA SUSPENSA (ALTURA)": "0141",
  "RESPIRADOR MOTORIZADO": "A2C2",
  "OCULOS": "0701",
  "MASCARA SOLDA C/ PROT. RESPI.": "A4C2",
  "HIDRAULICA": "B3F0",
  "LENTES": "0702",
  "Z3R0": "A404",
  "OCULOS COM GRAU": "A4A2",
  "ESPELHOS": "56",
  "BLOQUEIO DESCONTINUADO": "B7A3",
  "PELICULA SINALIZACAO": "B5G0",
  "CORRENTE SINALIZACAO": "B5E0",
  "FITA": "C1A3",
  "PLACA SINALIZACAO": "B5H0",
  "BARRA /BARREIRA SINALIZACAO": "B5J0",
  "ESTACAO FILTRANTE": "B4E0",
  "CARTAO IDENTIFICACAO BLOQUEIO": "B7G0",
  "Bloqueio": "B7",
  "PROTECAO CRANIANA": "B0",
  "LUVAS NITRILICAS": "0301",
  "PROT. AUDITIVA DESCONTINUADO": "A1B2",
  "Protecao Respiratoria": "A2",
  "SINALIZACAO": "2000",
  "CINTURAO PARAQUEDISTA": "A0A1",
  "DESENGRAXANTE": "B2B0",
  "JAPONAS": "B1G0",
  "ERGONOMIA": "B800",
  "M.R.O.": "C1",
  "ACESSORIOS CHUVEIRO/LAVA-OLHOS": "C7E0",
  "ANTISSEPTICO": "B2C0",
  "LUVA LATEX C/SUPORTE TEXTIL": "0331",
  "TELA SINALIZACAO": "B5F0",
  "TRAVA": "C1A4",
  "CALCA PROTECAO TERMICA (FRIO)": "C6B0",
  "Bidin": "4AA0",
  "EQUIPAMENTOS": "C1D0",
  "MEIA PROTECAO TERMICA (FRIO)": "C6E0",
  "TALABARTE": "A0A4",
  "Componentes E Acessorios": "0220",
  "LUVA ISOLANTE  CLASSE - 4": "A6E5",
  "LUVA ISOLANTE  CLASSE - 00": "A6E0",
  "LUVA ISOLANTE  CLASSE - 0": "A6E1",
  "LUVA ISOLANTE  CLASSE - 1": "A6E2",
  "LUVA ISOLANTE  CLASSE - 2": "A6E3",
  "BOLSA": "C0A0",
  "Uniformes": "B1",
  "VARA DE MANOBRA (ALTURA)": "0124",
  "TRAVA-QUEDA DIVERSOS": "A0B0",
  "FIXACAO": "C1A0",
  "ALTURA DESCONTINUADO": "A0A5",
  "ETIQUETA PARA IMPRESSORA": "C5C0",
  "AUTOMACAO": "C9",
  "MOCHILA": "C0C0",
  "Protecao Termica (Frio)": "C6",
  "KIT PRIMEIROS SOCORROS": "C8A2",
  "LUVA ISOLANTE  CLASSE - 3": "A6E4",
  "MEIO AMBIENTE": "C2A0",
  "Produto de Venda": "0007",
  "BLUSAO 3/4 COMBATE A INCENDIO": "B3A1",
  "PEDESTAL": "2040",
  "ALARME E BUZINA": "C1B0",
  "TALABARTES  (ALTURA)": "0110",
  "IMOBILIZACAO": "C8A1",
  "Higiene,Saude e Prot da Pele": "B2",
  "LENCOIS": "C1G0",
  "CINTURAO CADEIRINHA": "A0A3",
  "MOSQUETAO (ALTURA)": "0127",
  "CORRENTES": "2015",
  "Adesivo": "5BP3",
  "Medidores De Pressao": "0310",
  "DUTO AREA CLASSIFICADA": "B4H0",
  "CUTTER NIVEL 1": "B9A0",
  "SISTEMA ANTI-ATROPELAMENTO": "C9A0",
  "CARNEIRAS": "4602",
  "COMBATE A INCENDIO": "B3",
  "CONE P/BIRUTA": "CB",
  "MOSQUETOES E CONECTORES": "A0A8",
  "PALLET": "PLLT",
  "PALETO": "PLT",
  "ITENS DE MRO": "IDM0",
  "FERRAMENTAS": "F3R0",
  "CHAVE FERRAMENTA": "C0V3",
  "TAPETE ISOLANTE": "ZKA3"
};

const CAMPOS_CSV = {
  "codigo": "B1_COD",
  "descricao": "B1_DESC",
  "tipo": "B1_TIPO",
  "punidade": "B1_UM",
  "armazem": "B1_LOCPAD",
  "grupo": "B1_GRUPO",
  "blockg": "B1_MSBLQL",
  "sunidade": "B1_SEGUM",
  "fator": "B1_CONV",
  "tipofator": "B1_TIPCONV",
  "fornecedor": "B1_PROC",
  "loja": "B1_LOJPROC",
  "forncanal": "B1_MONO",
  "codigolinha": "B1_FPCOD",
  "marca": "B1_MARCA",
  "vendavel": "B1_VENDA",
  "origem": "B1_ORIGEM",
  "ncm": "B1_POSIPI",
  "multiplo": "B1_QE",
  "prazo": "B1_PE",
  "obs": "B1_OBS",
  "ca": "B1_CA",
  "vencimentoca": "B1_DTFINCA",
  "referencia": "B1_XCODCOM",
  "compras": "B1_XOBSOLE",
  "tipoblock": "B1_XTIPBLQ",
  "pesol": "B1_PESO",
  "pesob": "B1_PESBRU",
  "customizado": "B1_XCUSTOM"
};

const LINHAS_NUM = {
  "MRO": "C1",
  "ALTURA": "A0",
  "Pecas e Componentes exclusivos": "01",
  "ESPACO CONFINADO": "B4",
  "Materiais de Marcenaria e Carpintaria": "10",
  "CUTTER": "B9",
  "COMBATE A INCENDIO": "B3",
  "UNIFORME": "B1",
  "GERENCIAMENTO EPI": "C3",
  "Hidraulica e Pneumatica": "02",
  "Equipamentos de Transporte, Movimentacao": "48",
  "BLOQUEIO": "B7",
  "IMPERMEAVEL": "A8",
  "PROJETO/ENGENHARIA DESCONTINUADO": "SP",
  "PROTECAO RESPIRATORIA": "A2",
  "PROTECAO TERMICA(CALOR,FOGO,ARCO ELETRICO)": "A3",
  "PROTECAO QUIMICA": "A5",
  "LUVA": "A6",
  "Ferragens/acessorios": "4B",
  "Componentes eletronicos": "04",
  "CALCADO": "A7",
  "CAPACETE": "B0",
  "BOLSA": "C0",
  "PROTECAO VISUAL": "A4",
  "CHUVEIRO E LAVA-OLHOS": "C7",
  "DEMANDA DIRECIONADA (FAMILIA)": "X0",
  "Geracao e Distribuicao de energia": "06",
  "DESCARTAVEL": "A9",
  "HIGIENE, SAUDE E PROTECAO DA PELE": "B2",
  "Servicos Administrativos": "50",
  "Equipamentos Industriais": "46",
  "PROTECAO TERMICA (FRIO)": "C6",
  "Lampadas e acessorios de Iluminacao": "07",
  "Vestuario e Complementos": "34",
  "PROTECAO AUDITIVA": "A1",
  "IMPRESSORA": "C5",
  "Componentes eletricos": "05",
  "ERGONOMIA": "B8",
  "Capacetes": "8B",
  "Componentes de Instrumentacao": "03",
  "Construcao Civil": "08",
  "Materiais Metalicos": "20",
  "Equipamentos de Comunicacao e Informatica": "47",
  "PRIMEIROS SOCORROS": "C8",
  "Seguranca Pessoal e Industrial": "35",
  "MEIO AMBIENTE": "C2",
  "AUTOMACAO": "C9",
  "Produtos Quimicos": "24",
  "Aviamentos": "5B"
};

const LINHAS_NOMES = {
  "C1": "MRO",
  "A0": "ALTURA",
  "01": "Pecas e Componentes exclusivos",
  "B4": "ESPACO CONFINADO",
  "10": "Materiais de Marcenaria e Carpintaria",
  "B9": "CUTTER",
  "B3": "COMBATE A INCENDIO",
  "B1": "UNIFORME",
  "C3": "GERENCIAMENTO EPI",
  "02": "Hidraulica e Pneumatica",
  "48": "Equipamentos de Transporte, Movimentacao",
  "B7": "BLOQUEIO",
  "A8": "IMPERMEAVEL",
  "SP": "PROJETO/ENGENHARIA DESCONTINUADO",
  "A2": "PROTECAO RESPIRATORIA",
  "A3": "PROTECAO TERMICA(CALOR,FOGO,ARCO ELETRICO)",
  "A5": "PROTECAO QUIMICA",
  "A6": "LUVA",
  "4B": "Ferragens/acessorios",
  "04": "Componentes eletronicos",
  "A7": "CALCADO",
  "B0": "CAPACETE",
  "C0": "BOLSA",
  "A4": "PROTECAO VISUAL",
  "C7": "CHUVEIRO E LAVA-OLHOS",
  "X0": "DEMANDA DIRECIONADA (FAMILIA)",
  "06": "Geracao e Distribuicao de energia",
  "A9": "DESCARTAVEL",
  "B2": "HIGIENE, SAUDE E PROTECAO DA PELE",
  "50": "Servicos Administrativos",
  "46": "Equipamentos Industriais",
  "C6": "PROTECAO TERMICA (FRIO)",
  "07": "Lampadas e acessorios de Iluminacao",
  "34": "Vestuario e Complementos",
  "A1": "PROTECAO AUDITIVA",
  "C5": "IMPRESSORA",
  "05": "Componentes eletricos",
  "B8": "ERGONOMIA",
  "8B": "Capacetes",
  "03": "Componentes de Instrumentacao",
  "08": "Construcao Civil",
  "20": "Materiais Metalicos",
  "47": "Equipamentos de Comunicacao e Informatica",
  "C8": "PRIMEIROS SOCORROS",
  "35": "Seguranca Pessoal e Industrial",
  "MEIO AMBIENTE": "C2",
  "C9": "AUTOMACAO",
  "24": "Produtos Quimicos",
  "5B": "Aviamentos"
};

let produtos = [];

// Ordem fixa dos campos que APARECEM NA TABELA (depois do checkbox 'Selecionar')
const TABLE_ORDER = [
  "codigo", "descricao", "tamanho", "tipo", "punidade", "armazem", "grupo", "blockg", "sunidade", "fator",
  "tipofator", "fornecedor", "loja", "forncanal", "codigolinha", "marca", "vendavel", "origem", "ncm",
  "multiplo", "prazo", "obs", "ca", "vencimentoca", "referencia", "compras", "tipoblock", "pesol", "pesob", "customizado"
];

// Todos os campos do FORMULÁRIO (usados para leitura e limpeza). Inclui campos que não aparecem na tabela (ex: variavel, tipoCodPreenchimento)
const FORM_FIELDS = [
  "codigo", "descricao", "variavel", "tamanho", "tipo", "tipoCodPreenchimento", "punidade", "armazem", "grupo", "blockg",
  "sunidade", "fator", "tipofator", "fornecedor", "loja", "forncanal", "codigolinha", "marca", "vendavel", "origem",
  "ncm", "multiplo", "prazo", "obs", "ca", "vencimentoca", "referencia", "compras", "tipoblock", "pesol", "pesob", "customizado"
];


function iniciarPreenchimento() {
  // Tipos
  const listaTipos = document.getElementById("listaTipos");
  if (listaTipos) {
    listaTipos.innerHTML = "";
    for (let k in TIPOS_PRODUTO) {
      const o = document.createElement("option");
      o.value = TIPOS_PRODUTO[k];
      o.dataset.codigo = k;
      o.textContent = TIPOS_PRODUTO[k];
      listaTipos.appendChild(o);
    }
  }

  // Tipo código preenchimento
  const listaTipoCod = document.getElementById("listaTipoCodPreenchimento");
  if (listaTipoCod) {
    listaTipoCod.innerHTML = "";
    for (let k in TIPOS_PREENCHIMENTO) {
      const o = document.createElement("option");
      o.value = k;
      o.textContent = TIPOS_PREENCHIMENTO[k];
      listaTipoCod.appendChild(o);
    }
  }


  // Grupos
  const listaGrupos = document.getElementById("listaGrupos");
  if (listaGrupos) {
    listaGrupos.innerHTML = "";
    for (let k in GRUPOS_NUM) {
      const o = document.createElement("option");
      o.value = k;
      o.dataset.codigo = GRUPOS_NUM[k];
      o.label = `${k} (${GRUPOS_NUM[k]})`;
      listaGrupos.appendChild(o);
    }
  }

  // Bloqueio Geral
  const listaBlockg = document.getElementById("listaBlockg");
  if (listaBlockg) {
    ["1", "2"].forEach(v => {
      const o = document.createElement("option");
      o.value = v;
      listaBlockg.appendChild(o);
    });
  }

  // Tipo de fator
  const listaTipoFator = document.getElementById("listaTipoFator");
  if (listaTipoFator) {
    ["M", "D"].forEach(v => {
      const o = document.createElement("option");
      o.value = v;
      listaTipoFator.appendChild(o);
    });
  }

  // Lojas
  const listaLojas = document.getElementById("listaLojas");
  if (listaLojas) {
    ["01", "02", "03", "04", "05", "06", "07", "08", "09", "10"].forEach(v => {
      const o = document.createElement("option");
      o.value = v;
      listaLojas.appendChild(o);
    });
  }

  // Fornecedor Canal
  const listaFornCanal = document.getElementById("listaFornCanal");
  if (listaFornCanal) {
    ["S", "N"].forEach(v => {
      const o = document.createElement("option");
      o.value = v;
      listaFornCanal.appendChild(o);
    });
  }

  // Marcas
  const listaMarcas = document.getElementById("listaMarcas");
  if (listaMarcas) {
    listaMarcas.innerHTML = "";
    for (let sigla in MARCAS_NUM) {
      const codigo = MARCAS_NUM[sigla];
      const nome = MARCAS_NOMES[sigla] || sigla;
      const o = document.createElement("option");
      o.value = nome;            // usuário digita/vê o nome (ex: 3M)
      o.dataset.codigo = codigo; // mas guardamos o código numérico
      listaMarcas.appendChild(o);
    }
  }

  // Vendável
  const listaVendavel = document.getElementById("listaVendavel");
  if (listaVendavel) {
    ["S", "N"].forEach(v => {
      const o = document.createElement("option");
      o.value = v;
      listaVendavel.appendChild(o);
    });
  }

  // Compras
  const listaCompras = document.getElementById("listaCompras");
  if (listaCompras) {
    ["S", "N"].forEach(v => {
      const o = document.createElement("option");
      o.value = v;
      listaCompras.appendChild(o);
    });
  }

  // Customizado
  const listaCustomizado = document.getElementById("listaCustomizado");
  if (listaCustomizado) {
    ["S", "N"].forEach(v => {
      const o = document.createElement("option");
      o.value = v;
      listaCustomizado.appendChild(o);
    });
  }
}

// Linhas
const listaLinhas = document.getElementById("listaLinhas");
if (listaLinhas) {
  listaLinhas.innerHTML = "";
  for (let nome in LINHAS_NUM) {
    const cod = LINHAS_NUM[nome];
    const o = document.createElement("option");
    o.value = nome;          // funcionário vê o nome completo
    o.dataset.codigo = cod;  // mas guardamos o código real
    listaLinhas.appendChild(o);
  }
}

function pad(num, size) {
  let s = String(num ?? '');
  while (s.length < size) s = '0' + s;
  return s;
}

function gerarCodigoProduto() {
  const letra = (document.getElementById('tipoCodPreenchimento').value || '').trim().toUpperCase();
  const marcaNome = (document.getElementById('marca').value || '').trim();
  const variavel = (document.getElementById('variavel').value || '').trim();
  const tamanho = (document.getElementById('tamanho').value || '').trim();

  // 🔑 aqui está a diferença: convertemos NOME → SIGLA
  const marcaSigla = Object.keys(MARCAS_NOMES)
    .find(sigla => MARCAS_NOMES[sigla].toUpperCase() === marcaNome.toUpperCase()) || "";

  if (!letra || !marcaSigla || !variavel) {
    document.getElementById('codigo').value = '';
    return;
  }

  let codigo = 'SP' + letra + marcaSigla + pad(variavel, 2);
  if (tamanho) codigo += pad(tamanho, 2);

  document.getElementById('codigo').value = codigo;
}

['tipoCodPreenchimento', 'marca', 'variavel', 'tamanho'].forEach(id => {
  const el = document.getElementById(id);
  if (el) el.addEventListener('input', gerarCodigoProduto);
});




function adicionarProduto() {
  // Captura unidade de medida
  let unidadeInput = document.getElementById("punidade").value;
  let unidadeObj = UNIDADES.find(u => u.nome === unidadeInput || u.codigo === unidadeInput);
  let unidadeCodigo = unidadeObj ? unidadeObj.codigo : unidadeInput;

  const codigo = (document.getElementById('codigo').value || '').trim();
  const tipoCodPreenchimento = document.getElementById('tipoCodPreenchimento').value;
  const descricao = (document.getElementById('descricao').value || '').slice(0, 61);
  const variavel = (document.getElementById('variavel').value || '').trim();
  const tamanho = (document.getElementById('tamanho').value || '').trim();
  const marcaRef = (document.getElementById('marca').value || '').trim();
  const grupoNome = (document.getElementById('grupo').value || '').trim();

  if (!codigo || !tipoCodPreenchimento || !descricao || !variavel || !marcaRef) {
    alert('Preencha Código, Tipo Cód Preenchimento, Descrição, Variável e Marca.');
    return;
  }


  const produto = {};

  FORM_FIELDS.forEach(campoId => {
    // Marca: salvar o código (ex.: 005)
    if (campoId === 'marca') {
      const inputVal = marcaRef;
      const option = Array.from(document.getElementById("listaMarcas").options)
        .find(o => o.value === inputVal);
      // dataset.codigo tem o código (por ex., 005). Se não achar, tenta por dicionário global.
      produto[campoId] = option ? option.dataset.codigo
        : (MARCAS_NUM && MARCAS_NUM[inputVal]) ? MARCAS_NUM[inputVal] : '';
    }
    // Unidade de Medida: salvar sempre o código (ex.: PC)
    else if (campoId === 'punidade') {
      produto[campoId] = unidadeCodigo;
    }
    // Grupo: salvar o código (ex.: A1)
    else if (campoId === 'grupo') {
      const inputVal = grupoNome;
      let code = '';
      const option = Array.from(document.getElementById("listaGrupos").options)
        .find(o => o.value === inputVal);
      if (option && option.dataset && option.dataset.codigo) {
        code = option.dataset.codigo;
      } else if (GRUPOS_NUM && GRUPOS_NUM[inputVal]) {
        code = GRUPOS_NUM[inputVal];
      } else if (option && option.label) {
        // fallback: extrai código do label "NOME (A1)"
        const m = option.label.match(/\(([^)]+)\)/);
        if (m) code = m[1];
      }
      produto[campoId] = code || '';
    }
    // Cod. Linha: salvar a sigla/código (ex.: A6)
    else if (campoId === 'codigolinha') {
      const inputVal = (document.getElementById('codigolinha').value || '').trim();
      const option = Array.from(document.getElementById("listaLinhas").options)
        .find(o => o.value === inputVal);
      // dataset.codigo contem a sigla (A6). Se não achar, deixa vazio.
      produto[campoId] = option && option.dataset ? option.dataset.codigo : '';
    }
    // Campos numéricos / texto comuns
    else {
      const input = document.getElementById(campoId);
      const isCheckbox = input && input.type === 'checkbox';
      if (isCheckbox) {
        produto[campoId] = input.checked ? 'S' : 'N';
      } else if (input) {
        let val = (input.value || '').trim().toUpperCase();

        if (campoId === 'tipo') {
          const inputVal = (input.value || '').trim();
          // se digitou a sigla diretamente (ex: ME)
          if (TIPOS_PRODUTO[inputVal]) {
            produto[campoId] = inputVal;
          } else {
            const opt = Array.from(document.getElementById('listaTipos').options)
              .find(o => (o.value || '').toUpperCase() === inputVal.toUpperCase());
            produto[campoId] = opt && opt.dataset && opt.dataset.codigo ? opt.dataset.codigo : inputVal;
          }
        }
        else if (campoId === 'tipoCodPreenchimento') {
          produto[campoId] = TIPOS_PREENCHIMENTO[val] || val;
        }
        else if (campoId === 'descricao') {
          produto[campoId] = val.substring(0, 61);
        }
        else if (campoId === 'variavel') {
          produto[campoId] = pad(val, 2);
        }
        else if (campoId === 'tamanho') {
          produto[campoId] = tamanho ? pad(tamanho, 2) : '';
        }
        else {
          produto[campoId] = val;
        }
      } else {
        produto[campoId] = '';
      }
    }
  });

  produtos.push(produto);
  atualizarTabela();
  limparCampos();
}


function atualizarTabela() {
  const tbody = document.getElementById('tabelaProdutos').querySelector('tbody');
  tbody.innerHTML = '';
  produtos.forEach((prod, idx) => {
    const tr = document.createElement('tr');
    const tdSel = document.createElement('td');
    const cb = document.createElement('input');
    cb.type = 'checkbox'; cb.className = 'selecionar';
    tdSel.appendChild(cb);
    tr.appendChild(tdSel);

    TABLE_ORDER.forEach(campoId => {
      const td = document.createElement('td');
      let valor = prod[campoId] ?? '';
      if (campoId === 'tipoCodPreenchimento') valor = TIPOS_PREENCHIMENTO[valor] || valor;
      if (campoId === 'tipo') valor = TIPOS_PRODUTO[valor] || valor;
      td.textContent = valor;
      tr.appendChild(td);
    });

    tbody.appendChild(tr);
  });
}



function limparCampos() {
  FORM_FIELDS.forEach(campoId => {
    const input = document.getElementById(campoId);
    const fix = document.querySelector(`.fixar[data-target="${campoId}"]`);
    if (input && (!fix || !fix.checked)) {
      if (input.type === 'checkbox') input.checked = false;
      else input.value = '';
    }
  });
}


function exportarCSV() {
  const headerCodes = Object.values(CAMPOS_CSV);
  const headerLabels = [
    "Codigo", "Descricao", "Tipo", "Unidade Medida", "Armazem Padrao", "Grupo", "Bloqueado",
    "Segunda Unidade de Medida", "Fator de Conversão", "Tipo de Conversao", "Fornecedor Padrao",
    "Loja padrao", "Fornecedor Canal", "Cod. Linha", "Marca Produto", "Prod. Venda", "Origem",
    "NCM", "Quantidade Embalagem", "Prazo Entrega", "Observacao", "Certificado de aprovacao",
    "Vaencimento do Certificado", "Cod. Comercial", "Bloq. Compras", "Tipo de Bloqueio",
    "Peso Liq", "Peso Brut", "Prod.Custom"
  ];

  const linhas = [];
  linhas.push(headerCodes.join(";"));   // linha 1 = códigos
  linhas.push(headerLabels.join(";"));  // linha 2 = rótulos fixos

  produtos.forEach(prod => {
    const row = [];
    for (const [campoForm, codigoCampo] of Object.entries(CAMPOS_CSV)) {
      // busca pelo nome correto dentro de prod
      if (prod.hasOwnProperty(campoForm)) {
        row.push(prod[campoForm]);
      } else {
        row.push("");
      }
    }
    linhas.push(row.join(";"));
  });

  const csvString = linhas.join("\r\n");
  const blob = new Blob([csvString], { type: "text/csv;charset=utf-8;" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = "produtos.csv";
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

function excluirSelecionados() { const tbody = document.getElementById('tabelaProdutos').querySelector('tbody'); const linhas = Array.from(tbody.rows); const mant = []; for (let i = 0; i < linhas.length; i++) { const cb = linhas[i].querySelector('.selecionar'); if (cb && !cb.checked) mant.push(produtos[i]); } produtos = mant; atualizarTabela(); }

function toggleFixarTodos() {
  const fixarTodos = document.getElementById("fixarTodos").checked;
  const checkboxes = document.querySelectorAll(".fixar");

  checkboxes.forEach(chk => {
    const target = chk.getAttribute("data-target");
    // Pula os campos "descricao" e "tamanho"
    if (target === "descricao" || target === "tamanho" || target === "codigo") {
      chk.checked = false;
      return;
    }
    chk.checked = fixarTodos;
  });
}

function mostrarCadastro() { document.getElementById('sessao-cadastro').style.display = 'block'; document.getElementById('botao-abrir').style.display = 'none'; }
function fecharCadastro() { document.getElementById('sessao-cadastro').style.display = 'none'; document.getElementById('botao-abrir').style.display = 'inline-block'; }

// ENTER só funciona dentro do modalCadastro
const modal = document.getElementById("modalCadastro");

modal.addEventListener('keydown', function (e) {
  if (e.key === 'Enter') {
    e.preventDefault();
    adicionarProduto();
  }
});


window.onload = iniciarPreenchimento;


// Navegação entre seções
document.addEventListener("DOMContentLoaded", () => {
  const links = document.querySelectorAll("nav a[data-section]");
  links.forEach(link => {
    link.addEventListener("click", e => {
      e.preventDefault();
      const sectionId = link.getAttribute("data-section");

      document.querySelectorAll(".tela-inicial, .section").forEach(sec => {
        sec.classList.add("hidden");
        sec.classList.remove("active");
      });

      const target = document.getElementById(sectionId);
      if (target) {
        target.classList.remove("hidden");
        target.classList.add("active");
      }
    });
  });
});
// ==== CONTROLE DO MODAL DE CADASTRO ====

function abrirCadastroModal() {
  const modal = document.getElementById("modalCadastro");
  modal.style.display = "block";
}
function fecharCadastroModal() {
  const modal = document.getElementById("modalCadastro");
  modal.style.display = "none";

}


// Fecha o modal clicando fora do conteúdo
window.onclick = function (event) {
  const modal = document.getElementById("modalCadastro");
  if (event.target === modal) {
    fecharCadastroModal();
  }
};

// Fecha o modal quando apertar ESC
document.addEventListener('keydown', function (event) {
  if (event.key === "Escape") {
    fecharCadastroModal();
  }
});

// === Função auxiliar para pegar a sigla do tipo de produto ===

function getTipoCodigo(valorDigitado) {
  const lista = document.getElementById("listaTipos");
  if (!lista) return valorDigitado;
  const option = Array.from(lista.options).find(opt => (opt.value || '') === valorDigitado);
  return option && option.dataset && option.dataset.codigo ? option.dataset.codigo : valorDigitado;
}



// ENTER só funciona dentro do loginScreen
const loginScreen = document.getElementById("loginScreen");

loginScreen.addEventListener("keydown", function (e) {
  if (e.key === "Enter") {
    e.preventDefault();
    validarLogin();
  }
});
